"""Monthly projection engine for PAR endowment products."""

from par_model_v2.projection.monthly_projection import (
    AssetCashflowResult,
    AssetPosition,
    AssetShareResult,
    FullProjectionResult,
    LiabilityProjectionResult,
    ParEndowmentProduct,
    VALID_TERMS,
    project_asset_cashflows,
    project_asset_share,
    project_liability_cashflows,
    run_full_projection,
)
from par_model_v2.projection.fixed_income import (
    FixedIncomeInstrument,
    FixedIncomeProjectionResult,
    default_phase9_fixed_income_instruments,
    fixed_income_market_value_after_shock,
    project_fixed_income_cashflows,
)
from par_model_v2.projection.private_assets import (
    InfrastructureAsset,
    PrivateAsset,
    PrivateAssetProjectionResult,
    PrivateCreditAsset,
    PrivateEquityAsset,
    default_phase9_private_assets,
    project_private_asset_cashflows,
)
from par_model_v2.projection.derivatives import (
    BondForwardContract,
    DerivativeValuationResult,
    InterestRateSwapContract,
    bond_forward_cashflow_schedule,
    default_phase9_derivative_examples,
    interest_rate_swap_cashflow_schedule,
    value_bond_forward,
    value_derivative_portfolio,
    value_interest_rate_swap,
)
from par_model_v2.projection.asset_reporting import (
    AssetRollForwardReport,
    aggregate_asset_rollforward,
    project_phase9_asset_rollforward,
)
from par_model_v2.projection.asset_stress import (
    AssetStressReport,
    AssetStressScenario,
    default_phase9_asset_stress_scenarios,
    run_asset_class_stress_tests,
)
from par_model_v2.projection.hk_participating import (
    HKCashDividendMechanics,
    HKCashDividendPolicy,
    HKAssetShareSupportReport,
    HKDeclarationAssumption,
    HKLiabilityReportingPack,
    HKReversionaryBonusMechanics,
    HKReversionaryBonusPolicy,
    annual_cash_dividend_schedule,
    annual_reversionary_bonus_schedule,
    available_hk_cash_dividend_policy_ids,
    available_hk_reversionary_bonus_policy_ids,
    default_hk_cash_dividend_mechanics,
    default_hk_asset_share_fund_positions,
    default_hk_declaration_assumption,
    default_hk_reversionary_bonus_mechanics,
    build_hk_liability_reporting_pack,
    hk_bonus_supportability_view,
    hk_cash_dividend_asset_share_support_test,
    hk_declaration_sensitivity,
    hk_liability_management_summary,
    hk_liability_reserve_view,
    hk_liability_tvog_view,
    hk_reversionary_bonus_asset_share_support_test,
    reversionary_bonus_guarantee_split,
    sample_hk_cash_dividend_policies,
    sample_hk_cash_dividend_policy_table,
    sample_hk_reversionary_bonus_policies,
    sample_hk_reversionary_bonus_policy_table,
    validate_hk_cash_dividend_policy_table,
    validate_hk_reversionary_bonus_policy_table,
)
from par_model_v2.projection.chunked_processor import (  # noqa: F401
    ChunkRecord,
    ChunkStatus,
    ChunkedPortfolioProcessor,
    CheckpointStore,
    ProcessingPlan,
    ReconciliationCheck,
    ReconciliationReport,
    REQUIRED_CHUNK_RESULT_KEYS,
    build_chunk_plan,
    default_chunk_fn,
    failed_chunk_audit_report,
    reconcile_portfolio,
)
from par_model_v2.projection.portfolio_generator import (
    PortfolioGenerationConfig,
    PortfolioGenerationResult,
    PRODUCT_LINE_CASH,
    PRODUCT_LINE_RB,
    generate_hk_par_portfolio,
    iter_policy_chunks,
    load_portfolio,
    portfolio_digest,
    portfolio_summary,
    validate_portfolio,
    write_metadata,
    write_portfolio,
)
from par_model_v2.projection.hybrid_grid import (
    HybridGrid,
    HybridGridError,
    GridDimensionError,
)

__all__ = [
    "ParEndowmentProduct", "VALID_TERMS",
    "LiabilityProjectionResult", "project_liability_cashflows",
    "AssetPosition", "AssetCashflowResult", "project_asset_cashflows",
    "AssetShareResult", "project_asset_share",
    "FullProjectionResult", "run_full_projection",
    "HybridGrid", "HybridGridError", "GridDimensionError",
    "FixedIncomeInstrument", "FixedIncomeProjectionResult",
    "default_phase9_fixed_income_instruments",
    "fixed_income_market_value_after_shock", "project_fixed_income_cashflows",
    "InfrastructureAsset", "PrivateAsset", "PrivateAssetProjectionResult",
    "PrivateCreditAsset", "PrivateEquityAsset",
    "default_phase9_private_assets", "project_private_asset_cashflows",
    "BondForwardContract", "DerivativeValuationResult",
    "InterestRateSwapContract", "bond_forward_cashflow_schedule",
    "default_phase9_derivative_examples", "interest_rate_swap_cashflow_schedule",
    "value_bond_forward", "value_derivative_portfolio", "value_interest_rate_swap",
    "AssetRollForwardReport", "aggregate_asset_rollforward",
    "project_phase9_asset_rollforward",
    "AssetStressReport", "AssetStressScenario",
    "default_phase9_asset_stress_scenarios", "run_asset_class_stress_tests",
    "HKCashDividendMechanics", "HKCashDividendPolicy",
    "HKAssetShareSupportReport", "HKDeclarationAssumption",
    "HKLiabilityReportingPack",
    "HKReversionaryBonusMechanics", "HKReversionaryBonusPolicy",
    "annual_cash_dividend_schedule", "available_hk_cash_dividend_policy_ids",
    "annual_reversionary_bonus_schedule",
    "available_hk_reversionary_bonus_policy_ids",
    "default_hk_asset_share_fund_positions",
    "default_hk_cash_dividend_mechanics", "default_hk_declaration_assumption",
    "build_hk_liability_reporting_pack", "hk_bonus_supportability_view",
    "sample_hk_cash_dividend_policies",
    "default_hk_reversionary_bonus_mechanics",
    "hk_cash_dividend_asset_share_support_test", "hk_declaration_sensitivity",
    "hk_liability_management_summary", "hk_liability_reserve_view",
    "hk_liability_tvog_view",
    "hk_reversionary_bonus_asset_share_support_test",
    "reversionary_bonus_guarantee_split",
    "sample_hk_cash_dividend_policy_table", "sample_hk_reversionary_bonus_policies",
    "sample_hk_reversionary_bonus_policy_table", "validate_hk_cash_dividend_policy_table",
    "validate_hk_reversionary_bonus_policy_table",
    "PortfolioGenerationConfig", "PortfolioGenerationResult",
    "PRODUCT_LINE_CASH", "PRODUCT_LINE_RB",
    "generate_hk_par_portfolio", "iter_policy_chunks", "load_portfolio",
    "portfolio_digest", "portfolio_summary", "validate_portfolio",
    "write_metadata", "write_portfolio",
    # Phase 11 Task 2: chunked processing, checkpoint restart, reconciliation
    "ChunkRecord", "ChunkStatus", "ChunkedPortfolioProcessor",
    "CheckpointStore", "ProcessingPlan",
    "ReconciliationCheck", "ReconciliationReport",
    "REQUIRED_CHUNK_RESULT_KEYS",
    "build_chunk_plan", "default_chunk_fn",
    "failed_chunk_audit_report", "reconcile_portfolio",
]
