"""
Phase 21 Task 2 — Six-Driver Out-of-Sample Proxy Validation (FX included)
==========================================================================

Out-of-sample validation of a SIX-driver (G2++ short rate, equity, credit
spread, dynamic lapse, mortality trend, **FX translation**) LSMC economic-
capital proxy surface against high-accuracy nested truth on an independent,
disjoint-seed hold-out — completing the validation deliberately deferred from
Phase 21 Task 1 ("the nested benchmark is the only validated 6D ground truth
until Task 2 reports").

Methodology (mirrors the governed two-/three-/four-/five-driver validators)
----------------------------------------------------------------------------
* **State** ``x = (r_H, S_H, s_H, b_H, m_H, X_H)`` at the capital horizon,
  generated by the Phase 21 Task 1 six-driver outer construction
  (:meth:`SixDriverFXRiskAggregator._outer_states_6d`): G2++ 2F rates, GBM
  equity, CIR++ credit, OU lapse, OU mortality, lognormal FX, all off ONE
  shared 6-factor Cholesky-correlated antithetic draw under P.
* **Conditional liability decomposition** — the FX inner conditioning is
  analytic and CIP-exact (Phase 20 ``MART-FX-CIP``; Task 1), so::

      L6(x) = E^Q[L5 | r_H, S_H, s_H, b_H, m_H] + fx_l(X_H)

  with ``fx_l(X) = notional * (1 - X / X0)`` exact (no inner FX noise).  The
  noisy fitting target is one inner Q-path of L5 plus the exact FX term; the
  heavy hold-out truth is an ``n_inner_heavy``-path nested mean of L5 plus the
  exact FX term.  The five-driver inner nest is the governed HW1F nest
  conditioned at the realised G2++ ``r_H`` (Phase 20 documented residual).
* **Basis selection** sweeps a ``(degree, max_interaction_order)`` grid in TWO
  fx modes, all fitted on the SAME states + payoffs and selected jointly by
  OOS RMSE (or OOS R²) on the disjoint-seed hold-out:

  - ``"learned"`` — a hexavariate basis over all six state variables; the FX
    axis must be *estimated* from the noisy single-path fitting targets.
  - ``"analytic"`` — the CIP-exact FX leg is used as a known OFFSET (control
    variate): the polynomial spans only the five stochastic-valuation drivers
    and ``fx_l(X_H)`` is added back exactly in prediction.  This is the
    production-sensible design when part of the liability has a closed form
    (IFoA proxy-modelling WP structure-exploitation discipline).

  The head-to-head sweep documents the finding empirically: the learned FX
  coefficient has standard error ~``sigma_noise / (sqrt(n_fit) * sd(X_H))``,
  the same order as the true CIP slope at educational scale, so the offset
  mode is expected to dominate OOS — measured, not assumed.
* **Leakage + overfit diagnostics** — exact-state-sharing and min-distance
  evidence (`_leakage_nd`), in-sample(heavy) vs OOS R² gap per basis, and the
  overfit onset in basis-complexity order.
* **Capital comparison** — selected-surface proxy capital vs an independent
  six-driver nested benchmark evaluated on the SAME eval outer states
  (removes outer sampling noise from the proxy-vs-nested comparison; the
  remaining error is pure surface error — documented choice).

Staged execution (sandbox wall-clock discipline)
------------------------------------------------
``single_path_payoffs_sliced`` / ``heavy_targets_sliced`` spawn the FULL
per-state seed set (``SeedSequence(seed).spawn(n_full)``) and slice it, so a
staged run is bit-identical to a monolithic one (ASOP 56 reproducibility;
regression-tested).  ``validate(precomputed=...)`` consumes staged arrays.

EDUCATIONAL MODEL: placeholder parameters; not for production capital.

SOA ASOP 7 §3.3; ASOP 25 §3.3; ASOP 56 §3.1.3/§3.5; IA TAS M §3.2/§3.6;
IFoA proxy-modelling working party; Longstaff & Schwartz (2001).
"""

from __future__ import annotations

import hashlib
import json
import time
import uuid
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np

from par_model_v2.projection.monthly_projection import ParEndowmentProduct
from par_model_v2.projection.nested_stochastic_tvog import (
    capital_metrics_from_liabilities,
)
from par_model_v2.projection.multi_driver_capital_5d import (
    _inner_pathwise_pvs_5d,
    _n_quint_basis_terms,
    _quint_poly_basis,
)
from par_model_v2.projection.multi_driver_capital_6d_fx import (
    FXExposureSpec,
    SixDriverFXCorrelation,
    SixDriverFXRiskAggregator,
)
from par_model_v2.projection.multi_driver_proxy_validation import (
    CapitalComparison,
    LeakageDiagnostics,
    _leakage_nd,
    _r2,
    proxy_validation_use_restrictions,
)
from par_model_v2.stochastic.esg_process import FXParams, Measure

DEFAULT_CONFIDENCE_LEVEL = 0.995
DEFAULT_CAPITAL_HORIZON_MONTHS = 12

#: Default (degree, max_interaction_order) grid swept for the six-driver basis.
#: Mirrors the governed five-driver grid: the interaction cap is a genuine
#: complexity lever with six drivers, while the CIP-exact FX leg is exactly
#: LINEAR in X_H and additively separable — so a low-degree basis containing
#: the X monomial should already capture the FX axis exactly, and the sweep
#: verifies that empirically rather than assuming it.
DEFAULT_HEX_BASIS_GRID: Tuple[Tuple[int, int], ...] = (
    (1, 3), (2, 3), (3, 2), (3, 3), (4, 3),
)


# ---------------------------------------------------------------------------
# Hexavariate polynomial basis with capped interaction order
# ---------------------------------------------------------------------------

def _hex_poly_powers(
    degree: int, max_interaction_order: int = 3
) -> List[Tuple[int, int, int, int, int, int]]:
    """All exponent tuples (a,b,c,d,e,f) with total <= degree, where terms
    involving >= 3 distinct drivers are admitted only up to
    ``max_interaction_order`` total degree (IFoA basis discipline)."""
    if degree < 0:
        raise ValueError("degree must be >= 0")
    powers: List[Tuple[int, int, int, int, int, int]] = []
    for total in range(degree + 1):
        for a in range(total + 1):
            for b in range(total - a + 1):
                for c in range(total - a - b + 1):
                    for d in range(total - a - b - c + 1):
                        for e in range(total - a - b - c - d + 1):
                            f = total - a - b - c - d - e
                            nonzero = sum(
                                1 for ex in (a, b, c, d, e, f) if ex >= 1
                            )
                            if nonzero >= 3 and total > max_interaction_order:
                                continue
                            powers.append((a, b, c, d, e, f))
    return powers


def _hex_poly_basis(
    X: np.ndarray, degree: int, max_interaction_order: int = 3
) -> np.ndarray:
    """Hexavariate design matrix for X of shape (n, 6)."""
    X = np.asarray(X, dtype=float)
    if X.ndim != 2 or X.shape[1] != 6:
        raise ValueError("X must have shape (n, 6); got {}".format(X.shape))
    powers = _hex_poly_powers(degree, max_interaction_order)
    cols = [
        X[:, 0] ** a * X[:, 1] ** b * X[:, 2] ** c
        * X[:, 3] ** d * X[:, 4] ** e * X[:, 5] ** f
        for (a, b, c, d, e, f) in powers
    ]
    return np.column_stack(cols)


def _n_hex_basis_terms(degree: int, max_interaction_order: int = 3) -> int:
    return len(_hex_poly_powers(degree, max_interaction_order))


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class HexProxyValidationConfig:
    """Configuration for an out-of-sample SIX-DRIVER proxy-validation run.

    Mirrors :class:`QuintProxyValidationConfig`; adds the nested-benchmark
    sizing (``nested_n_inner`` heavy Q-paths at each of the shared eval
    states) because the six-driver nested truth is produced by the same
    heavy-target machinery rather than a separate engine class.
    """

    n_fit: int = 500
    n_validation: int = 60
    n_insample_heavy: int = 60
    n_inner_heavy: int = 384
    n_eval: int = 500
    nested_n_inner: int = 96
    basis_grid: Tuple[Tuple[int, int], ...] = DEFAULT_HEX_BASIS_GRID
    fx_modes: Tuple[str, ...] = ("analytic", "learned")
    selection_metric: str = "oos_rmse"
    confidence_level: float = DEFAULT_CONFIDENCE_LEVEL
    capital_horizon_months: int = DEFAULT_CAPITAL_HORIZON_MONTHS
    fit_seed: int = 42
    validation_seed: int = 20260607
    insample_heavy_seed: int = 7
    eval_seed_offset: int = 99
    nested_inner_seed_offset: int = 100
    outer_measure: Measure = Measure.P

    def __post_init__(self) -> None:
        if self.selection_metric not in ("oos_rmse", "oos_r2"):
            raise ValueError("selection_metric must be 'oos_rmse' or 'oos_r2'")
        if int(self.fit_seed) == int(self.validation_seed):
            raise ValueError(
                "fit_seed and validation_seed must differ to prevent hold-out leakage"
            )
        if not self.basis_grid:
            raise ValueError("basis_grid must be non-empty")
        for (d, m) in self.basis_grid:
            if d < 1:
                raise ValueError("all basis degrees must be >= 1")
            if m < 0:
                raise ValueError("all max_interaction_order values must be >= 0")
        if self.n_validation < 8:
            raise ValueError("n_validation must be >= 8 for a meaningful OOS metric")
        if not self.fx_modes:
            raise ValueError("fx_modes must be non-empty")
        for mode in self.fx_modes:
            if mode not in ("analytic", "learned"):
                raise ValueError("fx_modes entries must be 'analytic' or 'learned'")

    @property
    def eval_seed(self) -> int:
        return int(self.fit_seed) + int(self.eval_seed_offset)

    @property
    def nested_inner_seed(self) -> int:
        return int(self.fit_seed) + int(self.nested_inner_seed_offset)

    def to_dict(self) -> Dict[str, object]:
        return {
            "n_fit": self.n_fit,
            "n_validation": self.n_validation,
            "n_insample_heavy": self.n_insample_heavy,
            "n_inner_heavy": self.n_inner_heavy,
            "n_eval": self.n_eval,
            "nested_n_inner": self.nested_n_inner,
            "basis_grid": [list(p) for p in self.basis_grid],
            "fx_modes": list(self.fx_modes),
            "selection_metric": self.selection_metric,
            "confidence_level": self.confidence_level,
            "capital_horizon_months": self.capital_horizon_months,
            "fit_seed": self.fit_seed,
            "validation_seed": self.validation_seed,
            "insample_heavy_seed": self.insample_heavy_seed,
            "eval_seed": self.eval_seed,
            "nested_inner_seed": self.nested_inner_seed,
            "outer_measure": self.outer_measure.value
            if isinstance(self.outer_measure, Measure)
            else str(self.outer_measure),
        }


# ---------------------------------------------------------------------------
# Diagnostics / report containers
# ---------------------------------------------------------------------------

@dataclass
class HexBasisDiagnostics:
    """In/out-of-sample skill for one ``(fx_mode, degree, max_interaction_order)``."""

    fx_mode: str
    degree: int
    max_interaction_order: int
    n_basis_terms: int
    in_sample_r2_noisy: float
    in_sample_r2_heavy: float
    oos_rmse: float
    oos_r2: float
    oos_mae: float
    oos_max_abs_rel_error: float
    overfit_gap: float

    def to_dict(self) -> Dict[str, object]:
        return {
            "fx_mode": self.fx_mode,
            "degree": self.degree,
            "max_interaction_order": self.max_interaction_order,
            "n_basis_terms": self.n_basis_terms,
            "in_sample_r2_noisy": round(self.in_sample_r2_noisy, 6),
            "in_sample_r2_heavy": round(self.in_sample_r2_heavy, 6),
            "oos_rmse": round(self.oos_rmse, 6),
            "oos_r2": round(self.oos_r2, 6),
            "oos_mae": round(self.oos_mae, 6),
            "oos_max_abs_rel_error": round(self.oos_max_abs_rel_error, 6),
            "overfit_gap": round(self.overfit_gap, 6),
        }


@dataclass
class HexProxyValidationReport:
    """Full structured out-of-sample SIX-DRIVER proxy-validation report."""

    config: HexProxyValidationConfig
    basis_rows: List[HexBasisDiagnostics]
    selected_fx_mode: str
    selected_degree: int
    selected_max_interaction_order: int
    selection_metric: str
    overfit_onset_terms: Optional[int]
    leakage: LeakageDiagnostics
    capital_comparison: CapitalComparison
    fx_axis_evidence: Dict[str, float]
    reproducibility_digest: str
    run_id: str
    duration_seconds: float
    verdict: str
    notes: List[str] = field(default_factory=list)
    audit_entry_id: Optional[str] = None

    def selected_row(self) -> HexBasisDiagnostics:
        return next(
            r for r in self.basis_rows
            if r.fx_mode == self.selected_fx_mode
            and r.degree == self.selected_degree
            and r.max_interaction_order == self.selected_max_interaction_order
        )

    def to_dict(self) -> Dict[str, object]:
        return {
            "run_id": self.run_id,
            "verdict": self.verdict,
            "drivers": [
                "short_rate_g2pp_2f", "equity_level", "credit_spread",
                "lapse_behaviour", "mortality_trend", "fx_translation",
            ],
            "selected_fx_mode": self.selected_fx_mode,
            "selected_degree": self.selected_degree,
            "selected_max_interaction_order": self.selected_max_interaction_order,
            "selection_metric": self.selection_metric,
            "overfit_onset_terms": self.overfit_onset_terms,
            "selected_row": self.selected_row().to_dict(),
            "basis_rows": [r.to_dict() for r in self.basis_rows],
            "leakage": self.leakage.to_dict(),
            "capital_comparison": self.capital_comparison.to_dict(),
            "fx_axis_evidence": {
                k: round(float(v), 6) for k, v in self.fx_axis_evidence.items()
            },
            "reproducibility_digest": self.reproducibility_digest,
            "duration_seconds": round(self.duration_seconds, 4),
            "config": self.config.to_dict(),
            "notes": list(self.notes),
            "audit_entry_id": self.audit_entry_id,
            "standards": [
                "SOA ASOP 7 §3.3",
                "SOA ASOP 25 §3.3",
                "SOA ASOP 56 §3.5",
                "SOA ASOP 56 §3.1.3",
                "IA TAS M §3.6",
                "IA TAS M §3.2",
                "IFoA proxy-modelling working party",
                "Longstaff & Schwartz (2001)",
                "Solvency II Delegated Reg. Art. 188/234",
            ],
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)


@dataclass
class _FittedHexSurface:
    """A fitted six-driver capital surface in either fx mode.

    ``fx_mode == "learned"`` — ``beta`` spans the hexavariate basis over all
    six state variables and the prediction is the polynomial alone.
    ``fx_mode == "analytic"`` — ``beta`` spans the QUINTIVARIATE basis over
    the five stochastic-valuation drivers; the CIP-exact FX leg ``fx_l(X_H)``
    is added as a known offset by the validator (control-variate design).
    """

    beta: np.ndarray
    centers: np.ndarray
    scales: np.ndarray
    degree: int
    max_interaction_order: int
    fx_mode: str
    in_sample_r2_noisy: float

    @property
    def n_basis_terms(self) -> int:
        if self.fx_mode == "analytic":
            return _n_quint_basis_terms(self.degree, self.max_interaction_order)
        return _n_hex_basis_terms(self.degree, self.max_interaction_order)

    def predict_poly(self, X6: np.ndarray) -> np.ndarray:
        """Polynomial part only (no FX offset), from FULL (n, 6) states."""
        X6 = np.asarray(X6, dtype=float)
        if X6.ndim == 1:
            X6 = X6.reshape(1, -1)
        if self.fx_mode == "analytic":
            X = X6[:, :5]
            Xs = (X - self.centers) / self.scales
            return _quint_poly_basis(Xs, self.degree, self.max_interaction_order) @ self.beta
        Xs = (X6 - self.centers) / self.scales
        return _hex_poly_basis(Xs, self.degree, self.max_interaction_order) @ self.beta


def _fit_hex_surface(
    fit_X6: np.ndarray,
    fit_y5: np.ndarray,
    fx_l: np.ndarray,
    degree: int,
    max_interaction_order: int,
    fx_mode: str = "learned",
) -> _FittedHexSurface:
    """Least-squares fit of the six-driver ``(degree, max_int)`` surface.

    Same centring/scaling and ``np.linalg.lstsq`` protocol as the governed
    lower-dimensional engines, with the fitting data passed in so every basis
    is fitted on the *same* states + payoffs (comparable model selection).
    ``fit_y5`` is the noisy five-driver target and ``fx_l`` the exact FX leg:
    "learned" fits ``fit_y5 + fx_l`` on the hexavariate basis; "analytic" fits
    ``fit_y5`` on the quintivariate basis (FX handled as a known offset).
    """
    if fx_mode not in ("analytic", "learned"):
        raise ValueError("fx_mode must be 'analytic' or 'learned'")
    fit_X6 = np.asarray(fit_X6, dtype=float)
    if fit_X6.ndim != 2 or fit_X6.shape[1] != 6:
        raise ValueError("fit_X6 must have shape (n, 6)")
    if fx_mode == "analytic":
        X = fit_X6[:, :5]
        y = np.asarray(fit_y5, dtype=float)
        basis_fn = _quint_poly_basis
    else:
        X = fit_X6
        y = np.asarray(fit_y5, dtype=float) + np.asarray(fx_l, dtype=float)
        basis_fn = _hex_poly_basis
    centers = X.mean(axis=0)
    scales = X.std(axis=0, ddof=0)
    scales = np.where(scales > 0, scales, 1.0)
    Xs = (X - centers) / scales
    design = basis_fn(Xs, degree, max_interaction_order)
    beta, _resid, _rank, _sv = np.linalg.lstsq(design, y, rcond=None)
    y_hat = design @ beta
    ss_res = float(np.sum((y - y_hat) ** 2))
    ss_tot = float(np.sum((y - y.mean()) ** 2)) or 1.0
    return _FittedHexSurface(
        beta=beta, centers=centers, scales=scales, degree=int(degree),
        max_interaction_order=int(max_interaction_order), fx_mode=fx_mode,
        in_sample_r2_noisy=1.0 - ss_res / ss_tot,
    )


# ---------------------------------------------------------------------------
# Validator
# ---------------------------------------------------------------------------

class SixDriverFXProxyValidator:
    """Orchestrate fit / hold-out / basis-selection for the 6-driver proxy.

    Composes the Phase 21 Task 1 :class:`SixDriverFXRiskAggregator` for the
    governed six-driver outer-state construction and the FX exposure mapping;
    the five-driver inner Q-nest valuation (`_inner_pathwise_pvs_5d`) and the
    CIP-exact analytic FX term reproduce the Task 1 conditional liability
    exactly.  All heavy kernels expose ``*_sliced`` forms whose staged
    execution is bit-identical to a monolithic run.

    SOA ASOP 7 §3.3; ASOP 25 §3.3; ASOP 56 §3.5; IA TAS M §3.6; IFoA WP.
    """

    def __init__(
        self,
        product: ParEndowmentProduct,
        fx_params: Optional[FXParams] = None,
        fx_exposure: Optional[FXExposureSpec] = None,
        correlation6: Optional[SixDriverFXCorrelation] = None,
        capital_horizon_months: int = DEFAULT_CAPITAL_HORIZON_MONTHS,
        confidence_level: float = DEFAULT_CONFIDENCE_LEVEL,
        outer_measure: Measure = Measure.P,
        annual_qx_fn: Optional[Callable] = None,
        **aggregator_kwargs,
    ) -> None:
        if not (0 < capital_horizon_months < product.term_months):
            raise ValueError("capital_horizon_months must satisfy 0 < H < term_months")
        self.agg = SixDriverFXRiskAggregator(
            product,
            fx_params=fx_params,
            fx_exposure=fx_exposure,
            correlation6=correlation6,
            **aggregator_kwargs,
        )
        self.product = product
        self.capital_horizon_months = int(capital_horizon_months)
        self.confidence_level = float(confidence_level)
        self.outer_measure = Measure(outer_measure)
        self.annual_qx_fn = annual_qx_fn

    @property
    def _rem(self) -> int:
        return self.product.term_months - self.capital_horizon_months

    # -- state generation --------------------------------------------------- #
    def states(self, n: int, seed: int) -> np.ndarray:
        """(n, 6) outer states (r_H, S_H, s_H, b_H, m_H, X_H) — Task 1 kernel."""
        return self.agg._outer_states_6d(
            n, self.capital_horizon_months, self.outer_measure, seed
        )

    # -- analytic FX term (CIP-exact; no staging needed) --------------------- #
    def fx_term(self, states6: np.ndarray) -> np.ndarray:
        return self.agg.fx_exposure.liability_impact(
            np.asarray(states6, dtype=float)[:, 5]
        )

    # -- 5D inner kernels, slice-stable CRN ---------------------------------- #
    def _pvs_5d(self, row: np.ndarray, n_inner: int, inner_seed: int) -> np.ndarray:
        r, s, c, b, m = (float(v) for v in row[:5])
        return _inner_pathwise_pvs_5d(
            r, s, c, b, m, n_inner, self._rem,
            self.product, self.agg.hw_params, self.agg.gbm_params,
            self.agg.spread_params, self.agg.correlation,
            self.capital_horizon_months, inner_seed,
            self.agg.equity_guarantee, self.agg.credit_exposure,
            self.agg.lapse_exposure, self.agg.mortality_exposure,
            self.annual_qx_fn,
        )

    def single_path_payoffs_sliced(
        self, states6_full: np.ndarray, i0: int, i1: int, seed: int
    ) -> np.ndarray:
        """Noisy 5D single-inner-path payoffs for FULL-array rows [i0, i1).

        Spawns the FULL per-state seed set (``SeedSequence(seed + 1)``) and
        slices it, so any staging reproduces the monolithic values bit-for-bit.
        The exact FX term is NOT included (added analytically in validate()).
        """
        child = np.random.SeedSequence(seed + 1).spawn(len(states6_full))[i0:i1]
        y = np.empty(i1 - i0, dtype=float)
        for j in range(i1 - i0):
            inner_seed = int(child[j].generate_state(1)[0])
            y[j] = float(self._pvs_5d(states6_full[i0 + j], 1, inner_seed)[0])
        return y

    def heavy_targets_sliced(
        self, states6_full: np.ndarray, i0: int, i1: int, n_inner: int, seed: int
    ) -> np.ndarray:
        """High-accuracy nested E^Q[L5 | x] for FULL-array rows [i0, i1).

        Same slice-stable CRN protocol; FX term excluded (analytic, exact).
        """
        child = np.random.SeedSequence(seed).spawn(len(states6_full))[i0:i1]
        truth = np.empty(i1 - i0, dtype=float)
        for j in range(i1 - i0):
            inner_seed = int(child[j].generate_state(1)[0])
            truth[j] = float(self._pvs_5d(states6_full[i0 + j], n_inner, inner_seed).mean())
        return truth

    # -- main workflow -------------------------------------------------------- #
    def validate(
        self,
        config: Optional[HexProxyValidationConfig] = None,
        precomputed: Optional[Dict[str, np.ndarray]] = None,
        governance_store: Optional["object"] = None,
        actor: str = "SixDriverFXProxyValidator",
        phase: str = "Phase 21: FX + Liquidity Drivers and Six/Seven-Driver Economic Capital",
    ) -> HexProxyValidationReport:
        """Run the full disjoint-seed hold-out workflow.

        ``precomputed`` (staged execution) may supply any of the four heavy 5D
        arrays — ``fit_y5`` (n_fit), ``val_truth5`` (n_validation),
        ``insample_truth5`` (n_insample_heavy), ``nested_l5`` (n_eval) — each
        produced by the ``*_sliced`` kernels over the corresponding state set;
        missing keys are computed monolithically (bit-identical either way).
        """
        cfg = config or HexProxyValidationConfig()
        pre = precomputed or {}
        t0 = time.monotonic()
        run_id = "hx-proxyval-" + uuid.uuid4().hex[:8]
        notes: List[str] = []

        # --- 1. states (deterministic, cheap — always regenerated) ----------
        fit_X = self.states(cfg.n_fit, cfg.fit_seed)
        val_X = self.states(cfg.n_validation, cfg.validation_seed)
        eval_X = self.states(cfg.n_eval, cfg.eval_seed)

        # --- 2. fitting data: noisy 5D single path + exact FX term ----------
        fit_y5 = (
            np.asarray(pre["fit_y5"], dtype=float) if "fit_y5" in pre
            else self.single_path_payoffs_sliced(fit_X, 0, cfg.n_fit, cfg.fit_seed)
        )
        if len(fit_y5) != cfg.n_fit:
            raise ValueError("fit_y5 must have length n_fit")

        # --- 3. independent heavy hold-out (disjoint seed) -------------------
        val_truth5 = (
            np.asarray(pre["val_truth5"], dtype=float) if "val_truth5" in pre
            else self.heavy_targets_sliced(
                val_X, 0, cfg.n_validation, cfg.n_inner_heavy, cfg.validation_seed
            )
        )
        if len(val_truth5) != cfg.n_validation:
            raise ValueError("val_truth5 must have length n_validation")
        val_truth = val_truth5 + self.fx_term(val_X)

        # --- 4. held-in heavy subset (in/out skill gap) ----------------------
        n_in_heavy = min(cfg.n_insample_heavy, len(fit_X))
        insample_X = fit_X[:n_in_heavy]
        insample_truth5 = (
            np.asarray(pre["insample_truth5"], dtype=float) if "insample_truth5" in pre
            else self.heavy_targets_sliced(
                insample_X, 0, n_in_heavy, cfg.n_inner_heavy, cfg.insample_heavy_seed
            )
        )
        if len(insample_truth5) != n_in_heavy:
            raise ValueError("insample_truth5 must have length n_insample_heavy")
        insample_truth = insample_truth5 + self.fx_term(insample_X)

        # --- 5. leakage diagnostics ------------------------------------------
        leakage = _leakage_nd(fit_X, val_X, cfg.fit_seed, cfg.validation_seed)
        if not leakage.leakage_free:
            notes.append("WARNING: hold-out leakage check did not pass — review seeds.")

        # --- 6. basis sweep (both fx modes) on shared fitting data ------------
        fit_fx = self.fx_term(fit_X)
        val_fx = self.fx_term(val_X)
        insample_fx = self.fx_term(insample_X)

        def _predict_l6(surf: _FittedHexSurface, X6: np.ndarray, fx: np.ndarray) -> np.ndarray:
            poly = surf.predict_poly(X6)
            return poly + fx if surf.fx_mode == "analytic" else poly

        rows: List[HexBasisDiagnostics] = []
        surfaces: Dict[Tuple[str, int, int], _FittedHexSurface] = {}
        for mode in cfg.fx_modes:
            for (d, m) in cfg.basis_grid:
                surf = _fit_hex_surface(fit_X, fit_y5, fit_fx, d, m, fx_mode=mode)
                surfaces[(mode, d, m)] = surf
                val_pred = _predict_l6(surf, val_X, val_fx)
                in_pred = _predict_l6(surf, insample_X, insample_fx)
                resid = val_pred - val_truth
                denom = np.where(np.abs(val_truth) > 1e-9, np.abs(val_truth), 1.0)
                oos_rmse = float(np.sqrt(np.mean(resid ** 2)))
                oos_mae = float(np.mean(np.abs(resid)))
                oos_max_rel = float(np.max(np.abs(resid) / denom))
                oos_r2 = _r2(val_truth, val_pred)
                in_r2_heavy = _r2(insample_truth, in_pred)
                rows.append(HexBasisDiagnostics(
                    fx_mode=mode, degree=d, max_interaction_order=m,
                    n_basis_terms=surf.n_basis_terms,
                    in_sample_r2_noisy=surf.in_sample_r2_noisy,
                    in_sample_r2_heavy=in_r2_heavy,
                    oos_rmse=oos_rmse, oos_r2=oos_r2, oos_mae=oos_mae,
                    oos_max_abs_rel_error=oos_max_rel,
                    overfit_gap=in_r2_heavy - oos_r2,
                ))

        # --- 7. model selection by OOS skill (across modes AND bases) ---------
        if cfg.selection_metric == "oos_rmse":
            selected = min(rows, key=lambda r: r.oos_rmse)
        else:
            selected = max(rows, key=lambda r: r.oos_r2)
        selected_key = (selected.fx_mode, selected.degree, selected.max_interaction_order)

        # Overfit onset within the SELECTED mode (complexity ordering across
        # modes would mix non-nested bases).
        mode_rows = [r for r in rows if r.fx_mode == selected.fx_mode]
        ordered_mode = sorted(
            mode_rows, key=lambda r: (r.n_basis_terms, r.degree, r.max_interaction_order)
        )
        overfit_onset_terms: Optional[int] = None
        for prev, cur in zip(ordered_mode, ordered_mode[1:]):
            if cur.oos_rmse > prev.oos_rmse * 1.001:
                overfit_onset_terms = cur.n_basis_terms
                break
        ordered = sorted(
            rows, key=lambda r: (r.fx_mode, r.n_basis_terms, r.degree,
                                 r.max_interaction_order)
        )
        learned_best = min(
            (r for r in rows if r.fx_mode == "learned"),
            key=lambda r: r.oos_rmse, default=None,
        )
        analytic_best = min(
            (r for r in rows if r.fx_mode == "analytic"),
            key=lambda r: r.oos_rmse, default=None,
        )
        if learned_best is not None and analytic_best is not None:
            notes.append(
                "FX-mode head-to-head (best OOS RMSE): analytic offset {:.2f} vs "
                "learned hexavariate {:.2f} — the control-variate design {} the "
                "fully-learned FX axis at this educational scale.".format(
                    analytic_best.oos_rmse, learned_best.oos_rmse,
                    "dominates" if analytic_best.oos_rmse <= learned_best.oos_rmse
                    else "does NOT dominate")
            )

        # --- 8. capital comparison at the selected basis -----------------------
        chosen = surfaces[selected_key]
        eval_fx = self.fx_term(eval_X)
        proxy_l = _predict_l6(chosen, eval_X, eval_fx)
        proxy_capital = capital_metrics_from_liabilities(
            proxy_l, cfg.confidence_level, cfg.capital_horizon_months
        )
        nested_l5 = (
            np.asarray(pre["nested_l5"], dtype=float) if "nested_l5" in pre
            else self.heavy_targets_sliced(
                eval_X, 0, cfg.n_eval, cfg.nested_n_inner, cfg.nested_inner_seed
            )
        )
        if len(nested_l5) != cfg.n_eval:
            raise ValueError("nested_l5 must have length n_eval")
        nested_l = nested_l5 + self.fx_term(eval_X)
        nested_capital = capital_metrics_from_liabilities(
            nested_l, cfg.confidence_level, cfg.capital_horizon_months
        )
        notes.append(
            "Proxy and nested capital are evaluated on the SAME eval outer states "
            "(seed {}), so the comparison isolates pure surface error; the nested "
            "benchmark uses {} heavy inner Q-paths per state.".format(
                cfg.eval_seed, cfg.nested_n_inner)
        )

        def _rel(a: float, b: float) -> float:
            return abs(a - b) / (abs(b) if abs(b) > 1e-9 else 1.0)

        capital_cmp = CapitalComparison(
            proxy_capital=proxy_capital, nested_capital=nested_capital,
            var_rel_error=_rel(proxy_capital.var_liability, nested_capital.var_liability),
            es_rel_error=_rel(proxy_capital.es_liability, nested_capital.es_liability),
            scr_rel_error=_rel(proxy_capital.scr_proxy, nested_capital.scr_proxy),
            nested_n_outer=cfg.n_eval, nested_n_inner=cfg.nested_n_inner,
        )

        # --- 9. FX-axis recovery evidence --------------------------------------
        # The CIP-exact FX leg is exactly linear in X_H with slope
        # -notional / X0; verify the selected surface recovered it by linear
        # projection of the surface's partial FX effect on the hold-out.
        x0 = float(self.agg.fx_exposure.initial_spot_rate)
        notional = float(self.agg.fx_exposure.exposure_notional)
        theoretical_slope = -notional / x0
        x_col = val_X[:, 5]
        base = val_X.copy()
        base[:, 5] = x0
        base_fx = self.fx_term(base)  # exactly zero at X = X0
        partial_fx = _predict_l6(chosen, val_X, val_fx) - _predict_l6(chosen, base, base_fx)
        slope_fit = (
            float(np.polyfit(x_col - x0, partial_fx, 1)[0])
            if np.std(x_col) > 0 else float("nan")
        )
        fx_axis_evidence = {
            "theoretical_fx_slope": theoretical_slope,
            "recovered_fx_slope": slope_fit,
            "slope_rel_error": abs(slope_fit - theoretical_slope)
            / max(abs(theoretical_slope), 1e-9),
        }
        notes.append(
            "FX-axis recovery: surface partial-FX slope {:.2f} vs CIP-exact "
            "theoretical {:.2f} (rel err {:.2%}).".format(
                slope_fit, theoretical_slope, fx_axis_evidence["slope_rel_error"])
        )

        # --- 10. reproducibility digest ----------------------------------------
        digest = hashlib.sha256(
            np.round(np.concatenate([
                val_truth, chosen.beta,
                np.array([1.0 if selected.fx_mode == "analytic" else 0.0,
                          selected.degree, selected.max_interaction_order,
                          proxy_capital.var_liability, proxy_capital.es_liability],
                         dtype=float),
            ]), 9).tobytes()
        ).hexdigest()

        # --- 11. verdict ---------------------------------------------------------
        verdict = self._verdict(selected, capital_cmp, leakage, fx_axis_evidence, notes)

        duration = time.monotonic() - t0

        audit_entry_id = None
        if governance_store is not None:
            try:
                from par_model_v2.governance.audit_trail import AuditEntry

                entry = AuditEntry.model_run(
                    actor=actor, phase=phase, run_id=run_id,
                    scenario_count=cfg.n_fit
                    + (cfg.n_validation + n_in_heavy) * cfg.n_inner_heavy
                    + cfg.n_eval * cfg.nested_n_inner,
                    duration_seconds=round(duration, 4),
                    outcome="PASS" if verdict.startswith("PASS") else "PARTIAL",
                    files_changed=[
                        "par_model_v2/projection/multi_driver_proxy_validation_6d.py"
                    ],
                    test_summary=(
                        "6D OOS proxy-val: selected ({}, deg={}, max_int={}), OOS R2={:.4f}, "
                        "OOS RMSE={:.2f}, VaR rel err={:.2%}, leakage_free={}, "
                        "fx_slope_rel_err={:.2%}".format(
                            selected.fx_mode, selected.degree,
                            selected.max_interaction_order,
                            selected.oos_r2, selected.oos_rmse,
                            capital_cmp.var_rel_error, leakage.leakage_free,
                            fx_axis_evidence["slope_rel_error"])
                    ),
                )
                governance_store.audit_trail.append(entry)
                audit_entry_id = entry.entry_id
            except Exception as exc:  # pragma: no cover - governance optional
                notes.append("audit append skipped: {}".format(exc))

        return HexProxyValidationReport(
            config=cfg, basis_rows=ordered,
            selected_fx_mode=selected.fx_mode,
            selected_degree=selected.degree,
            selected_max_interaction_order=selected.max_interaction_order,
            selection_metric=cfg.selection_metric,
            overfit_onset_terms=overfit_onset_terms,
            leakage=leakage, capital_comparison=capital_cmp,
            fx_axis_evidence=fx_axis_evidence,
            reproducibility_digest=digest, run_id=run_id, duration_seconds=duration,
            verdict=verdict, notes=notes, audit_entry_id=audit_entry_id,
        )

    @staticmethod
    def _verdict(
        selected: HexBasisDiagnostics,
        capital_cmp: CapitalComparison,
        leakage: LeakageDiagnostics,
        fx_axis_evidence: Dict[str, float],
        notes: List[str],
    ) -> str:
        """Honest PASS / PARTIAL verdict against documented thresholds.

        Thresholds (educational; mirror the five-driver gate, plus the FX-axis
        recovery check): OOS R^2 >= 0.95, selected-basis VaR rel error <= 10%,
        hold-out leakage-free, overfit gap <= 0.05, and the surface's partial
        FX slope within 10% of the CIP-exact theoretical slope.
        """
        reasons: List[str] = []
        if selected.oos_r2 < 0.95:
            reasons.append("OOS R^2 {:.4f} < 0.95".format(selected.oos_r2))
        if capital_cmp.var_rel_error > 0.10:
            reasons.append("VaR rel error {:.2%} > 10%".format(capital_cmp.var_rel_error))
        if not leakage.leakage_free:
            reasons.append("hold-out not leakage-free")
        if selected.overfit_gap > 0.05:
            reasons.append("overfit gap {:.4f} > 0.05".format(selected.overfit_gap))
        if fx_axis_evidence["slope_rel_error"] > 0.10:
            reasons.append(
                "FX-axis slope rel error {:.2%} > 10%".format(
                    fx_axis_evidence["slope_rel_error"])
            )
        if reasons:
            notes.append("verdict drivers: " + "; ".join(reasons))
            return "PARTIAL — " + "; ".join(reasons)
        return (
            "PASS — selected basis (deg {}, max_int {}) validated OOS "
            "(R^2={:.4f}, VaR rel err={:.2%}, leakage-free, overfit gap={:.4f}, "
            "FX axis recovered within {:.2%})".format(
                selected.degree, selected.max_interaction_order, selected.oos_r2,
                capital_cmp.var_rel_error, selected.overfit_gap,
                fx_axis_evidence["slope_rel_error"])
        )


# ---------------------------------------------------------------------------
# Use restrictions / limitations (IA TAS M §3.5 disclosure)
# ---------------------------------------------------------------------------

def hex_proxy_validation_use_restrictions() -> Dict[str, object]:
    """Structured model-use restrictions for the SIX-DRIVER OOS proxy validation."""
    base = proxy_validation_use_restrictions()
    base.update({
        "module": "par_model_v2/projection/multi_driver_proxy_validation_6d.py::SixDriverFXProxyValidator",
        "classification": "EDUCATIONAL ONLY — six-driver proxy-model validation evidence, not a regulatory sign-off",
        "what_it_validates": (
            "Out-of-sample skill of the Phase 21 HEXAVARIATE (G2++ rate + equity "
            "+ credit-spread + lapse-behaviour + mortality-trend + FX-translation) "
            "LSMC capital surface against high-accuracy nested truth on an "
            "independent, disjoint-seed hold-out, with the basis (polynomial "
            "degree AND capped higher-order interaction order) selected by OOS "
            "error, plus an explicit FX-axis recovery check against the "
            "CIP-exact analytic FX leg."
        ),
        "selection_caveat": (
            "Basis selection minimises OOS error over the swept (degree, "
            "max_interaction_order) grid only; the true optimum may lie outside "
            "the grid. Valid only over the fitted 6-D interquartile state region "
            "— extrapolation is unsupported."
        ),
        "residual_risk": (
            "The FX leg is a single linear translation exposure with CIP-exact "
            "conditioning — real books carry optioned / partially hedged FX with "
            "smile and regime (peg) dynamics outside this surface. Liquidity risk "
            "remains outside the proxy (Phase 21 Task 3). The five-driver inner "
            "nest is the governed HW1F nest conditioned at the realised G2++ r_H "
            "(Phase 20 residual). Parameters are illustrative placeholders; "
            "capital magnitudes are NOT calibrated."
        ),
        "standards": [
            "SOA ASOP 7 §3.3", "SOA ASOP 25 §3.3", "SOA ASOP 56 §3.5",
            "SOA ASOP 56 §3.1.3", "IA TAS M §3.6", "IA TAS M §3.2",
            "IFoA proxy-modelling working party", "Longstaff & Schwartz (2001)",
            "Solvency II Delegated Reg. Art. 188/234",
        ],
    })
    return base


def hex_proxy_validation_use_restrictions_json() -> str:
    return json.dumps(hex_proxy_validation_use_restrictions(), indent=2, sort_keys=True)


__all__ = [
    "DEFAULT_HEX_BASIS_GRID",
    "HexProxyValidationConfig",
    "HexBasisDiagnostics",
    "HexProxyValidationReport",
    "SixDriverFXProxyValidator",
    "_fit_hex_surface",
    "_hex_poly_basis",
    "_hex_poly_powers",
    "_n_hex_basis_terms",
    "hex_proxy_validation_use_restrictions",
    "hex_proxy_validation_use_restrictions_json",
]
# Phase 21 Task 2 module — end of file.
