"""
Five-Driver Capital Re-Aggregation with the Two-Factor G2++ Rates Driver
========================================================================

Phase 20 Task 4 (capital re-aggregation half).  Re-runs the Phase 19 Task 4
five-driver tail-dependent aggregation
(:mod:`par_model_v2.projection.multi_driver_capital_5d_aggregation`) with the
**two-factor G2++** rates driver of Phase 20 Tasks 1-3 substituted for the
single-factor Hull-White (HW1F) rate driver in the OUTER real-world state, so
the rate-risk marginal that feeds economic capital now carries a genuine
second (slope / curvature) factor.

What this module is, and is NOT
-------------------------------
* It is **additive**: it imports, but never modifies, the five-driver nested
  primitives, the HW1F-based inner valuation, the var-covar / copula
  aggregation, and the Phase 20 calibrated G2++ parameters.
* The **OUTER** rate state ``r_H`` is generated by the calibrated G2++ two-factor
  short rate ``r(t) = phi(t) + x(t) + y(t)`` (exact-OU factor recursions), anchored
  to the SAME initial risk-free curve as the HW1F baseline, so the only thing that
  changes between the HW1F and G2++ runs is the *rate driver dynamics* — the
  comparison isolates the capital impact of the second factor + the swaption-
  calibrated factor volatilities/correlation.
* The **INNER** conditional valuation ``L(r_H, S_H, s_H, b_H, m_H)`` is reused
  verbatim from the five-driver engine: it conditions the governed HW1F Q nest at
  the realised ``r_H``.  In other words the G2++ driver enters the *outer
  real-world rate marginal and its tail*; the conditional liability *operator*
  ``L(.)`` is the governed nested operator.  This is the standard real-world-outer
  / risk-neutral-inner economic-capital decomposition (ASOP 56 §3.5).  Surfacing a
  fully G2++-consistent inner nest is recorded as a residual (Task 5 / future work).

Cross-driver correlation
-------------------------
The governed 5x5 ESG correlation couples the *rate* axis to equity / credit /
lapse / mortality.  With the two-factor driver the dominant factor ``x`` inherits
that governed cross-correlation (it is driven by the same correlated rate shock
``z_rate`` as the HW1F baseline), while the second factor ``y`` is correlated to
``x`` by the calibrated G2++ factor correlation ``rho`` and is otherwise
orthogonal to the four non-rate drivers.  This injects the second factor as a new
orthogonal curve-shape tail axis without disturbing the governed ESG block — a
documented, conservative modelling choice (ASOP 25 §3.3; IFoA Aggregation WP).

SOA ASOP 56 §3.5; SOA ASOP 56 §3.1; SOA ASOP 25 §3.3; SOA ASOP 7 §3.3;
IA TAS M §3.2/§3.5/§3.6; Solvency II Delegated Reg. Art. 234; Brigo-Mercurio (2006);
IFoA Life Aggregation & Simulation WP.
"""

from __future__ import annotations

import hashlib
import math
import time
import uuid
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np

from par_model_v2.projection.monthly_projection import ParEndowmentProduct
from par_model_v2.projection.nested_stochastic_tvog import (
    DEFAULT_CAPITAL_HORIZON_MONTHS,
    capital_metrics_from_liabilities,
)
from par_model_v2.projection.multi_driver_capital_5d import (
    FiveDriverCorrelation,
    _correlated_shocks_5,
)
from par_model_v2.projection.multi_driver_capital_5d_aggregation import (
    FiveDriverAggregationConfig,
    FiveDriverAggregationReport,
    FiveDriverRiskAggregator,
    FiveDriverStandaloneCapital,
    FiveDriverVarCovarAggregation,
)
from par_model_v2.projection.multi_driver_copula_aggregation import (
    CopulaAggregationConfig,
    CopulaRiskAggregator,
)
from par_model_v2.stochastic.esg_process import (
    CorrelationMatrixValidator,
    GBMEquityProcess,
    G2PlusParams,
    Measure,
    RiskFreeCurve,
)
from par_model_v2.stochastic.credit_spread import CreditSpreadProcess
from par_model_v2.stochastic.lapse_behaviour import LapseBehaviourProcess
from par_model_v2.stochastic.mortality_trend import MortalityTrendProcess


# ---------------------------------------------------------------------------
# Phase 20 Task 2 swaption-calibrated G2++ parameters (educational proxy)
# ---------------------------------------------------------------------------

#: G2++ parameters from the Phase 20 Task 2 swaption-surface calibration
#: (G-SWPN PASS 7/7; vol RMSE 54.7 bps).  See
#: docs/validation/PHASE20_TASK2_G2PP_SWAPTION_REPORT.json.
CALIBRATED_G2PP_PARAMS: Dict[str, float] = {
    "mean_reversion_x": 0.0345437806981911,
    "mean_reversion_y": 0.9582779369460774,
    "vol_x": 0.006369513208373254,
    "vol_y": 0.0024001097598661688,
    "factor_correlation": -0.9082136050335214,
}


def calibrated_g2pp_params() -> G2PlusParams:
    """Return the Phase 20 Task 2 swaption-calibrated :class:`G2PlusParams`."""
    return G2PlusParams(
        mean_reversion_x=CALIBRATED_G2PP_PARAMS["mean_reversion_x"],
        mean_reversion_y=CALIBRATED_G2PP_PARAMS["mean_reversion_y"],
        vol_x=CALIBRATED_G2PP_PARAMS["vol_x"],
        vol_y=CALIBRATED_G2PP_PARAMS["vol_y"],
        factor_correlation=CALIBRATED_G2PP_PARAMS["factor_correlation"],
        initial_x=0.0,
        initial_y=0.0,
    )


# ---------------------------------------------------------------------------
# Two-factor G2++ outer-state sampler
# ---------------------------------------------------------------------------

def _outer_states_5d_g2pp(
    aggregator: FiveDriverRiskAggregator,
    g2pp_params: G2PlusParams,
    n_outer: int,
    capital_horizon_months: int,
    measure: Measure,
    seed: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Project ``n_outer`` outer paths to H with a G2++ two-factor rate driver.

    Returns ``(outer_states, g2pp_short_rate_paths)`` where ``outer_states`` is the
    (n, 5) array ``(r_H, S_H, s_H, b_H, m_H)`` consumed by the unchanged
    five-driver inner valuation, and ``g2pp_short_rate_paths`` is the (n, H+1)
    G2++ short-rate path used as the equity-drift driver.

    The dominant G2++ factor ``x`` is driven by the SAME governed, 5x5-correlated
    rate shock ``z_rate`` as the HW1F baseline (preserving the ESG cross-
    correlation); the second factor ``y`` is correlated to ``x`` by the calibrated
    factor correlation ``rho`` and otherwise orthogonal.  ``r_H`` is anchored to the
    initial-curve instantaneous forward (so the level matches the HW1F baseline)
    and dispersed by the calibrated factor volatilities (the genuine 2F uplift).
    """
    gbm_params = aggregator.gbm_params
    rng = np.random.default_rng(seed)
    chol = aggregator.correlation.cholesky(gbm_params.rate_equity_correlation)
    z_rate, z_equity, z_spread, z_lapse, z_mort = _correlated_shocks_5(
        rng, n_outer, capital_horizon_months, chol
    )

    curve = aggregator.initial_curve if aggregator.initial_curve is not None else RiskFreeCurve.flat(
        aggregator.hw_params.initial_short_rate
    )

    # Second G2++ factor shock: correlate to the rate shock by the calibrated rho,
    # keep its idiosyncratic part orthogonal to all four non-rate drivers.
    rho = float(g2pp_params.factor_correlation)
    z_indep = rng.standard_normal((n_outer, capital_horizon_months))
    z_y = rho * z_rate + math.sqrt(max(0.0, 1.0 - rho * rho)) * z_indep

    a = float(g2pp_params.mean_reversion_x)
    b = float(g2pp_params.mean_reversion_y)
    sigma = float(g2pp_params.vol_x)
    eta = float(g2pp_params.vol_y)
    dt = 1.0 / 12.0
    mx = math.exp(-a * dt)
    my = math.exp(-b * dt)
    sx = sigma * math.sqrt((1.0 - math.exp(-2.0 * a * dt)) / (2.0 * a))
    sy = eta * math.sqrt((1.0 - math.exp(-2.0 * b * dt)) / (2.0 * b))

    steps = capital_horizon_months
    x = np.empty((n_outer, steps + 1), dtype=float)
    y = np.empty((n_outer, steps + 1), dtype=float)
    r = np.empty((n_outer, steps + 1), dtype=float)
    x[:, 0] = float(g2pp_params.initial_x)
    y[:, 0] = float(g2pp_params.initial_y)
    # Deterministic anchor phi(t) = initial-curve instantaneous forward at t.
    phi0 = float(curve.instantaneous_forward(0.0))
    r[:, 0] = phi0 + x[:, 0] + y[:, 0]
    for month in range(steps):
        x[:, month + 1] = mx * x[:, month] + sx * z_rate[:, month]
        y[:, month + 1] = my * y[:, month] + sy * z_y[:, month]
        phi = float(curve.instantaneous_forward(float(month + 1) * dt))
        r[:, month + 1] = phi + x[:, month + 1] + y[:, month + 1]

    # Equity / credit / lapse / mortality: same building blocks and shocks as the
    # HW1F baseline; equity drift uses the G2++ short-rate path for consistency.
    gbm = GBMEquityProcess(gbm_params, rate_process=None)
    csp = CreditSpreadProcess(aggregator.spread_params)
    lap = LapseBehaviourProcess(aggregator.lapse_params)
    mor = MortalityTrendProcess(aggregator.mortality_params)

    equity_paths, _ret = gbm._simulate_array(
        n_outer, capital_horizon_months, measure, r, z_equity
    )
    spread_paths = csp._simulate_array(n_outer, capital_horizon_months, measure, z_spread)
    lapse_paths = lap._simulate_array(n_outer, capital_horizon_months, measure, z_lapse)
    mort_paths = mor._simulate_array(n_outer, capital_horizon_months, measure, z_mort)

    r_h = r[:, capital_horizon_months]
    s_h = equity_paths[:, capital_horizon_months]
    c_h = spread_paths[:, capital_horizon_months]
    b_h = lapse_paths[:, capital_horizon_months]
    m_h = mort_paths[:, capital_horizon_months]
    return np.column_stack([r_h, s_h, c_h, b_h, m_h]), r


# ---------------------------------------------------------------------------
# G2++ five-driver risk aggregator
# ---------------------------------------------------------------------------

class G2ppFiveDriverRiskAggregator(FiveDriverRiskAggregator):
    """Five-driver standalone capital + var-covar / copula aggregation with the
    two-factor G2++ rate driver in the OUTER state.

    Identical to :class:`FiveDriverRiskAggregator` except the outer ``(r,S,s,b,m)``
    state is generated by :func:`_outer_states_5d_g2pp`.  The inner conditional
    valuation, the var-covar (5x5 ESG) aggregation, the copula-on-realised-losses
    aggregation and the nested benchmark are all reused unchanged.
    """

    def __init__(self, *args, g2pp_params: Optional[G2PlusParams] = None, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.g2pp_params = g2pp_params if g2pp_params is not None else calibrated_g2pp_params()
        #: Populated by run() so downstream tail diagnostics can reuse the realised
        #: CRN-isolated and full loss vectors without a second pass.
        self.last_loss_vectors = None

    def run(
        self,
        config: Optional[FiveDriverAggregationConfig] = None,
        governance_store: Optional["object"] = None,
        actor: str = "G2ppFiveDriverRiskAggregator",
        phase: str = "Phase 20: Market-Consistency and Multi-Factor Uplift",
    ) -> FiveDriverAggregationReport:
        cfg = config or FiveDriverAggregationConfig()
        if cfg.capital_horizon_months >= self.product.term_months:
            raise ValueError("capital_horizon_months must be less than product term")

        t0 = time.monotonic()
        run_id = "g2pp-ftd-riskagg-" + uuid.uuid4().hex[:8]

        outer, _r_paths = _outer_states_5d_g2pp(
            self, self.g2pp_params, cfg.n_outer, cfg.capital_horizon_months,
            cfg.outer_measure, cfg.seed,
        )
        (rate_l, equity_l, credit_l, lapse_l, mortality_l,
         full_l) = self._component_liabilities(outer, cfg)
        crn_sum_l = rate_l + equity_l + credit_l + lapse_l + mortality_l
        self.last_loss_vectors = {
            "rate": rate_l, "equity": equity_l, "credit": credit_l,
            "lapse": lapse_l, "mortality": mortality_l, "full": full_l,
            "crn_sum": crn_sum_l,
        }

        conf = cfg.confidence_level
        hm = cfg.capital_horizon_months
        rate_cap = capital_metrics_from_liabilities(rate_l, conf, hm)
        equity_cap = capital_metrics_from_liabilities(equity_l, conf, hm)
        credit_cap = capital_metrics_from_liabilities(credit_l, conf, hm)
        lapse_cap = capital_metrics_from_liabilities(lapse_l, conf, hm)
        mortality_cap = capital_metrics_from_liabilities(mortality_l, conf, hm)
        full_cap = capital_metrics_from_liabilities(full_l, conf, hm)
        crn_sum_cap = capital_metrics_from_liabilities(crn_sum_l, conf, hm)

        stacked = np.vstack([rate_l, equity_l, credit_l, lapse_l, mortality_l])
        loss_corr = np.nan_to_num(np.corrcoef(stacked), nan=0.0)
        loss_corr_t = tuple(tuple(float(x) for x in row) for row in loss_corr)

        scr_vec = np.array(
            [rate_cap.scr_proxy, equity_cap.scr_proxy, credit_cap.scr_proxy,
             lapse_cap.scr_proxy, mortality_cap.scr_proxy], dtype=float
        )
        standalone_sum = float(scr_vec.sum())

        C = self.correlation.matrix(self.gbm_params.rate_equity_correlation)
        C_t = tuple(tuple(float(x) for x in row) for row in C)
        corr_report = CorrelationMatrixValidator().validate_matrix(C_t, repair=False)

        aggregated_variance = float(scr_vec @ C @ scr_vec)
        correlated_scr = float(np.sqrt(max(0.0, aggregated_variance)))

        nested_scr = float(full_cap.scr_proxy)
        gap = correlated_scr - nested_scr
        rel_err = _rel_error(correlated_scr, nested_scr)
        denom = abs(nested_scr) if abs(nested_scr) > 1e-9 else 1.0
        understatement_pct = (nested_scr - correlated_scr) / denom
        interaction_residual = float(crn_sum_cap.scr_proxy - nested_scr)
        interaction_residual_rel = interaction_residual / denom

        var_covar = FiveDriverVarCovarAggregation(
            esg_correlation_matrix=C_t,
            correlation_matrix_passed=bool(corr_report.passed),
            correlated_scr=correlated_scr,
            full_nested_capital=full_cap,
            crn_additive_capital=crn_sum_cap,
            interaction_residual_scr=interaction_residual,
            interaction_residual_rel=interaction_residual_rel,
            diversification_benefit_formula=standalone_sum - correlated_scr,
            diversification_benefit_nested=standalone_sum - nested_scr,
            formula_vs_nested_scr_gap=gap,
            formula_vs_nested_scr_rel_error=rel_err,
            esg_understatement_pct=understatement_pct,
        )
        standalone = FiveDriverStandaloneCapital(
            rate_capital=rate_cap, equity_capital=equity_cap,
            credit_capital=credit_cap, lapse_capital=lapse_cap,
            mortality_capital=mortality_cap,
            standalone_scr_sum=standalone_sum, loss_correlation_matrix=loss_corr_t,
        )

        copula_cfg = CopulaAggregationConfig(
            n_sim=cfg.n_sim_copula, seed=cfg.seed + 11,
            confidence_level=conf, capital_horizon_months=hm,
        )
        copula = CopulaRiskAggregator(
            loss_vectors=[rate_l, equity_l, credit_l, lapse_l, mortality_l],
            driver_names=["rate", "equity", "credit", "lapse", "mortality"],
            nested_scr=nested_scr,
            var_covar_scr=correlated_scr,
        ).run(config=copula_cfg)

        p = self.g2pp_params
        notes: List[str] = [
            "RATE DRIVER = two-factor G2++ r(t)=phi(t)+x(t)+y(t) (Phase 20 Task 2 swaption "
            "calibration: a={:.4f}, b={:.4f}, sigma={:.5f}, eta={:.5f}, rho={:.4f}), anchored to "
            "the same initial curve as the HW1F baseline; only the rate dynamics differ.".format(
                p.mean_reversion_x, p.mean_reversion_y, p.vol_x, p.vol_y, p.factor_correlation),
            "Dominant factor x carries the governed 5x5 ESG cross-correlation (same z_rate as HW1F); "
            "second factor y is correlated to x by rho and otherwise orthogonal - a new curve-shape "
            "tail axis (ASOP 25 §3.3).",
            "SCOPE: the two-factor driver enters the OUTER real-world rate marginal/tail; the INNER "
            "conditional liability L(.) reuses the governed HW1F Q nest at the realised r_H (standard "
            "real-world-outer / risk-neutral-inner decomposition, ASOP 56 §3.5). A fully G2++-consistent "
            "inner nest is a documented residual.",
            "Var-covar aggregation uses the governed 5x5 ESG driver correlation; MR-010 (the var-covar "
            "understatement of the diversified nested capital) refreshed under the 2F rate driver: "
            "understatement {:.1f}%.".format(100.0 * understatement_pct),
            "Copula-on-realised-losses (selected: {}) reconciles to nested capital within {:.1f}% - the "
            "MR-010 mitigation, re-confirmed with the 2F rate driver (MR-012 tail-aggregation "
            "governance).".format(copula.selected_copula, 100.0 * copula.selected.scr_rel_error_vs_nested),
            "CRN additive decomposition leaves a {:.1f}%-of-nested interaction residual (multiplicative "
            "in-force x equity-guarantee and in-force x mortality-G cross-terms); unchanged in kind by the "
            "2F rate driver.".format(100.0 * interaction_residual_rel),
        ]
        verdict = self._verdict(cfg, standalone, var_covar, copula, notes)

        digest = hashlib.sha256(
            np.round(
                np.concatenate([
                    full_l, rate_l, equity_l, credit_l, lapse_l, mortality_l,
                    np.array([correlated_scr, nested_scr,
                              copula.selected.aggregated_capital.scr_proxy], dtype=float),
                    C.ravel(),
                    np.array([p.mean_reversion_x, p.mean_reversion_y, p.vol_x, p.vol_y,
                              p.factor_correlation], dtype=float),
                ]),
                9,
            ).tobytes()
        ).hexdigest()

        duration = time.monotonic() - t0
        audit_entry_id = None
        if governance_store is not None:
            try:
                from par_model_v2.governance.audit_trail import AuditEntry

                entry = AuditEntry.model_run(
                    actor=actor, phase=phase, run_id=run_id,
                    scenario_count=cfg.n_outer * cfg.n_inner * 6,
                    duration_seconds=round(duration, 4),
                    outcome=verdict.split()[0],
                    files_changed=[
                        "par_model_v2/projection/multi_driver_capital_5d_g2pp.py"
                    ],
                    test_summary=(
                        "G2PP-2F rate driver; rate={:.1f}; equity={:.1f}; credit={:.1f}; "
                        "lapse={:.1f}; mortality={:.1f}; var-cov={:.1f} (rel {:.1%}); "
                        "copula({})={:.1f} (rel {:.1%}); nested={:.1f}; ESG understatement={:.1f}%".format(
                            rate_cap.scr_proxy, equity_cap.scr_proxy,
                            credit_cap.scr_proxy, lapse_cap.scr_proxy,
                            mortality_cap.scr_proxy, correlated_scr, rel_err,
                            copula.selected_copula,
                            copula.selected.aggregated_capital.scr_proxy,
                            copula.selected.scr_rel_error_vs_nested,
                            nested_scr, 100.0 * understatement_pct,
                        )
                    ),
                )
                governance_store.audit_trail.append(entry)
                audit_entry_id = entry.entry_id
            except Exception as exc:  # pragma: no cover - governance optional
                notes.append("Governance audit append skipped: {}".format(exc))

        return FiveDriverAggregationReport(
            config=cfg,
            drivers=("short_rate_g2pp_2f", "equity_guarantee", "credit_spread",
                     "lapse_behaviour", "mortality_trend"),
            standalone=standalone, var_covar=var_covar, copula=copula,
            nested_scr=nested_scr, run_id=run_id, duration_seconds=duration,
            verdict=verdict, reproducibility_digest=digest, notes=notes,
            audit_entry_id=audit_entry_id,
        )


def _rel_error(value: float, reference: float) -> float:
    denom = abs(reference) if abs(reference) > 1e-9 else 1.0
    return abs(value - reference) / denom


__all__ = [
    "CALIBRATED_G2PP_PARAMS",
    "calibrated_g2pp_params",
    "G2ppFiveDriverRiskAggregator",
]
