"""Post-Phase-IGUI Task 6 - design-note builder (pre-registration only).

Pre-registers ONE stochastic-model improvement candidate - RQMC + control-variates
variance reduction for the OUTER capital (SCR) loop (MR-VR-2) - with fixed acceptance
gates, Phase-30-stop-rule bound. Pure governance: NO model parameter change, NO new
copula-structure candidate, implementation DEFERRED to next cycle.

Outputs:
  docs/validation/POSTIGUI_TASK6_DESIGN_NOTE.{json,md}
  docs/POSTIGUI_OUTER_LOOP_EFFICIENCY_DESIGN_CARD.md
  optional governance ChangeRecord (--governance), governance_change, OWNER_REVIEW.
"""

from __future__ import annotations

import json
import os
import sys

from par_model_v2.projection.outer_loop_efficiency_design import (
    CANDIDATE_ID,
    CANDIDATE_TITLE,
    COMPLETED_PRIOR_CANDIDATE_ID,
    COMPLETED_POOL,
    FROZEN_T_COMPONENT_SCR_REFERENCE,
    NESTED_PATHWISE_SCR_REFERENCE,
    NEXT_CANDIDATE_ID,
    affected_components,
    design_note,
    standard_references,
    validate_design_note,
)
from par_model_v2.governance.audit_trail import AuditEntry, ChangeRecord, GovernanceStore

GOV_PATH = os.path.join(".claude-dev", "GOVERNANCE_STORE.json")
OUT_DIR = os.path.join("docs", "validation")
JSON_PATH = os.path.join(OUT_DIR, "POSTIGUI_TASK6_DESIGN_NOTE.json")
MD_PATH = os.path.join(OUT_DIR, "POSTIGUI_TASK6_DESIGN_NOTE.md")
CARD_PATH = os.path.join("docs", "POSTIGUI_OUTER_LOOP_EFFICIENCY_DESIGN_CARD.md")

CHANGE_TITLE = (
    "Post-Phase-IGUI Task 6 - design note: pre-register ONE model-improvement "
    "candidate (MR-VR-2 RQMC + control-variates variance reduction for the OUTER "
    "capital/SCR loop, Phase 30 stop-rule bound)"
)


def _md(note: dict, gate: dict) -> str:
    lines = [
        f"# {note['title']}",
        "",
        f"**Verdict: {'PASS' if gate['ok'] else 'FAIL'}** - pure governance "
        f"({note['change_type']}); NO parameter change; implementation DEFERRED. "
        f"Classification: {note['classification']}.",
        "",
        "## 1. Candidate (pre-registered, exactly one)",
        "",
        f"- **{note['candidate_id']}** - {note['candidate_title']}",
        f"- Touches copula structure: **{note['touches_copula_structure']}** "
        f"(Phase 30 stop-rule compliant)",
        f"- No model parameter change: **{note['no_model_parameter_changes']}**; "
        f"implementation deferred: **{note['implementation_deferred']}**",
        f"- Techniques under study: {', '.join(note['vr_techniques'])}",
        "",
        "## 2. Context",
        "",
        note["context"],
        "",
        "Frozen cross-check references:",
        "",
        f"- Governed frozen-t component SCR: **{note['frozen_references']['frozen_t_component_scr']:,.6f}**",
        f"- Nested path-wise reference: {note['frozen_references']['nested_pathwise_scr']:,.1f}",
        "- MR-VR-1 inner-loop variance-reduction results (work-normalised, crude=1.0):",
        "",
    ]
    for k, v in note["frozen_references"]["inner_loop_vr_results"].items():
        lines.append(f"  - {k}: {v:g}x")
    lines.append("")
    lines.append("- Outer-basis scrambled-Sobol RQMC precedents (work-normalised, crude=1.0):")
    lines.append("")
    for k, v in note["frozen_references"]["outer_rqmc_precedents"].items():
        lines.append(f"  - {k}: {v:g}x")
    lines.extend([
        "",
        "## 3. Scope deferred to next cycle (implementation)",
        "",
    ])
    for s in note["scope_deferred_next_cycle"]:
        lines.append(f"- {s}")
    lines.extend(["", "## 4. Pre-registered acceptance gates (frozen now)", ""])
    for g in note["acceptance_gates"]:
        lines.append(f"- **{g['id']} - {g['name']}.** {g['criterion']}")
    lines.extend([
        "",
        "## 5. Candidate sequencing",
        "",
        f"- Completed pool (efficiency/diagnostics): {', '.join(note['candidate_sequencing']['completed_pool'])}",
        f"- Selected now: **{note['candidate_sequencing']['selected_now']}**",
        f"- Next candidate: **{note['candidate_sequencing']['next_candidate']}** (deferred, owner sign-off)",
        "",
        note["candidate_sequencing"]["rationale"],
        "",
        "## 6. Owner-decision note",
        "",
        note["owner_decision_note"],
        "",
        "## 7. Stop-rule compliance",
        "",
        note["stop_rule_compliance"],
        "",
        "## 8. Standard references",
        "",
    ])
    for r in note["standard_references"]:
        lines.append(f"- {r}")
    lines.extend([
        "",
        f"## 9. Self-consistency gate: {'PASS' if gate['ok'] else 'FAIL'} "
        f"({sum(1 for v in gate['checks'].values() if v)}/{gate['n_checks']} checks)",
        "",
        "*Generated by scripts/build_postigui_task6_design_note.py.*",
        "",
    ])
    return "\n".join(lines)


def _card(note: dict) -> str:
    return "\n".join([
        "# Post-Phase-IGUI Outer-Loop Efficiency Design Card (MR-VR-2)",
        "",
        f"**{note['candidate_id']} - {note['candidate_title']}.** Pure governance "
        f"pre-registration; NO parameter change; implementation DEFERRED. "
        f"{note['classification']} only.",
        "",
        "## What it would do (next cycle, gated)",
        "",
        "Run a DISCLOSED efficiency study on the OUTER capital / SCR loop: compare crude "
        "i.i.d. Monte Carlo against scrambled-Sobol randomised-QMC over the outer "
        "scenario grid, a control variate built from the cheap closed-form / proxy SCR, "
        "and an optional proportional tail stratification - all targeting the governed "
        "99.5% SCR over the SAME governed model. Report unbiasedness (control beta fit "
        "out-of-sample; RQMC mean over >= 200 scramble seeds within 0.5% of crude), "
        "work-normalised variance-reduction ratios with CIs at the 99.5% target, the "
        "control-target correlation rho with realised reduction 1/(1-rho^2), and the "
        "outer scenario count n* for a target SCR SE. The governed production estimator "
        f"and headline SCR ({FROZEN_T_COMPONENT_SCR_REFERENCE:,.1f}) stay BIT-IDENTICAL "
        "- this is measurement, not adoption.",
        "",
        "## Why now",
        "",
        "MR-CAL-1 calibration diagnostics (Task 2) and MR-VR-1 inner-path variance "
        "reduction (Task 4/5) are both COMPLETE. MR-VR-1 helped the MEAN-TVOG target a "
        "great deal but recorded antithetic as INEFFECTIVE (1.31x) at the 99.5% "
        "quantile - which is exactly the OUTER loop's target. The remaining admissible "
        "numerical gain is on the OUTER SCR estimator, where RQMC and a control variate "
        "are the bias-free levers that suit a tail target.",
        "",
        "## Sequencing",
        "",
        f"1. **MR-CAL-1** credentialled-data calibration diagnostics (COMPLETE, Task 2).",
        f"2. **{COMPLETED_PRIOR_CANDIDATE_ID}** inner-path antithetic/CRN/RQMC variance reduction for TVOG (COMPLETE, Task 4/5).",
        f"3. **{CANDIDATE_ID}** RQMC + control-variates for the OUTER capital/SCR loop (selected now).",
        f"4. **{NEXT_CANDIDATE_ID}** longevity 5th driver (deferred; needs owner sign-off).",
        "",
        "*Generated by scripts/build_postigui_task6_design_note.py.*",
        "",
    ])


def apply_governance(store: GovernanceStore, note: dict, gate: dict) -> dict:
    actor = "PostIGUITask6OuterLoopEfficiencyDesignNote"
    phase = "Post-Phase-IGUI: Model-Improvement Candidate Pre-Registration"
    if any(r.title == CHANGE_TITLE for r in store.change_records):
        return {"added": False, "reason": "already applied (idempotent)"}
    rec = ChangeRecord.create(
        title=CHANGE_TITLE,
        description=(
            "Design note pre-registering exactly ONE stochastic-model improvement "
            "candidate (MR-VR-2: RQMC + control-variates variance reduction for the "
            "OUTER capital/SCR loop) with six fixed acceptance gates and a "
            "governed-headline invariance requirement. Efficiency study only, no "
            "estimator adoption; MR-CAL-1 and MR-VR-1 are COMPLETE and MR-LONGEV-1 "
            "(longevity 5th driver) stays deferred. No capital output changed; no new "
            "copula-structure candidate (Phase 30 binding stop-rule); MR-016/MR-017 "
            "untouched."
        ),
        change_type="governance_change",
        affected_components=affected_components(),
        standard_references=standard_references(),
        before_snapshot={
            "frontier": "Post-Phase-IGUI Task 5 COMPLETE (MR-VR-1 offline-UI panel)",
            "mr016": "OPEN (stop-rule applied; dependence-FORM escalation ended)",
            "mr017": "OPEN (vine-form limitations)",
            "next_task": "Post-Phase-IGUI Task 6 model-improvement candidate design note",
        },
        after_snapshot={
            "candidate_id": CANDIDATE_ID,
            "completed_pool": list(COMPLETED_POOL),
            "next_candidate": NEXT_CANDIDATE_ID,
            "acceptance_gates": [g["id"] for g in note["acceptance_gates"]],
            "validation_gate_ok": gate["ok"],
            "implementation": "DEFERRED to next cycle (gated)",
        },
        impact_assessment=(
            "Governance only. Freezes the candidate identity, scope and acceptance "
            "gates before any implementation; the governed frozen-t headline is "
            "unchanged and no model parameter moves. Only the Monte Carlo sampling "
            "scheme (RQMC point set) of an existing outer estimator would change, plus "
            "an unbiased control variate. Stop-rule honoured (no copula structure "
            "touched)."
        ),
        author=actor,
        phase=phase,
        quantitative_impact=(
            f"Registered references only: governed headline "
            f"{FROZEN_T_COMPONENT_SCR_REFERENCE:,.6f}; nested "
            f"{NESTED_PATHWISE_SCR_REFERENCE:,.1f}; MR-VR-1 inner-loop results "
            "{Sobol 2241x / CRN 18.9x / antithetic 1.88x mean, antithetic 1.31x at "
            "99.5% = ineffective}; outer-basis Sobol precedents 2.76x-7.1x. No governed "
            "capital figures changed."
        ),
    )
    rec.submit_for_peer_review(
        actor=actor,
        comments="Candidate pre-registration + six fixed gates + sequencing; scaffold tests added.",
    )
    rec.submit_to_owner(
        actor=actor,
        comments="Owner review: pure governance pre-registration; implementation deferred to next cycle.",
    )
    store.add_change_record(rec)
    store.audit_trail.append(AuditEntry.governance(
        actor=actor,
        phase=phase,
        event="ChangeRecord opened (OWNER_REVIEW) - Post-Phase-IGUI Task 6 candidate design note",
        details={"record_id": rec.record_id, "change_type": "governance_change",
                 "status": rec.status.value, "candidate_id": CANDIDATE_ID},
    ))
    return {"added": True, "record_id": rec.record_id, "status": rec.status.value}


def main(use_governance: bool = False) -> dict:
    note = design_note()
    gate = validate_design_note(note)
    note["validation_gate"] = gate
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(note, fh, indent=1, default=float)
    with open(MD_PATH, "w", encoding="utf-8") as fh:
        fh.write(_md(note, gate))
    with open(CARD_PATH, "w", encoding="utf-8") as fh:
        fh.write(_card(note))
    out = {"verdict": "PASS" if gate["ok"] else "FAIL", "gate_ok": gate["ok"],
           "n_checks": gate["n_checks"], "candidate_id": CANDIDATE_ID,
           "json": JSON_PATH, "md": MD_PATH, "card": CARD_PATH}
    if use_governance:
        store = GovernanceStore.from_json(open(GOV_PATH).read())
        gov = apply_governance(store, note, gate)
        if gov.get("added"):
            with open(GOV_PATH, "w", encoding="utf-8") as fh:
                fh.write(store.to_json())
        gov["audit_entries"] = len(store.audit_trail.all())
        gov["audit_integrity_ok"] = store.audit_trail.verify_all()
        gov["change_records_total"] = len(store.change_records)
        out["governance"] = gov
    return out


if __name__ == "__main__":
    res = main(use_governance="--governance" in sys.argv)
    print(json.dumps(res, indent=1, default=str))
