"""Phase 32 Task 1 - zero-install offline UI consolidation design note builder.

Renders the pre-registered design note (baseline audit + gap list +
acceptance criteria, see par_model_v2.viewer.ui_consolidation), runs the
Task 1 gate (structural + LIVE repo cross-checks), and writes:

  docs/validation/PHASE32_TASK1_DESIGN_NOTE.{json,md}
  docs/UI_CONSOLIDATION_DESIGN_CARD.md

Pure governance_change (--governance), left in OWNER_REVIEW.
NO model parameter changes; the Phase 30 binding stop-rule stands.
"""

from __future__ import annotations

import json
import os
import sys

from par_model_v2.governance.audit_trail import AuditEntry, ChangeRecord, GovernanceStore
from par_model_v2.viewer.ui_consolidation import (
    DOC_ID,
    DOC_VERSION,
    design_note,
    validate_design_note,
)

GOV_PATH = os.path.join(".claude-dev", "GOVERNANCE_STORE.json")
OUT_DIR = os.path.join("docs", "validation")
JSON_PATH = os.path.join(OUT_DIR, "PHASE32_TASK1_DESIGN_NOTE.json")
MD_PATH = os.path.join(OUT_DIR, "PHASE32_TASK1_DESIGN_NOTE.md")
CARD_PATH = os.path.join("docs", "UI_CONSOLIDATION_DESIGN_CARD.md")

CHANGE_TITLE = (
    "Phase 32 Task 1 - zero-install offline UI consolidation design note; "
    "baseline audit green (3 self-tests, 0 network / 0 JS errors, 0 external "
    "refs, contract 1.13.0, 13 tabs); 3 gaps pre-registered (G1 owner pack "
    "surface, G2 user-input run results, G3 governed read-out sweep)"
)

STANDARD_REFERENCES = [
    "IFoA Model Practice Note (MPN) section 4 (documentation and communication)",
    "SOA ASOP 41 (actuarial communications - clarity for the intended user)",
    "SOA ASOP 56 sections 3.1.3, 3.4, 3.6 (model risk, reliance, documentation)",
]

AFFECTED_COMPONENTS = [
    "par_model_v2/viewer/ui_consolidation.py",
    "tests/test_phase32_task1_design_note.py",
    "scripts/build_phase32_task1_design_note.py",
    "docs/validation/PHASE32_TASK1_DESIGN_NOTE.{json,md}",
    "docs/UI_CONSOLIDATION_DESIGN_CARD.md",
]


def _md(note: dict, gate: dict) -> str:
    md, base = note["metadata"], note["baseline_audit"]
    lines = [
        "# Zero-Install Offline UI Consolidation - Design Note (Phase 32 Task 1)",
        "",
        f"**Doc** `{md['doc_id']}` v{md['doc_version']} | {md['phase']} | "
        f"classification {md['classification']} | model parameter changes: "
        f"{'NONE' if md['no_model_parameter_changes'] else 'YES'} | "
        f"gate: **{'PASS' if gate['ok'] else 'FAIL'}** ({gate['n_checks']} checks)",
        "",
        "## Standing directive",
        "",
        md["directive"],
        "",
        "## (a) Baseline audit (measured, frozen as cross-check targets)",
        "",
        f"- measured at {base['measured_at_utc']}",
    ]
    for k in ("ui_app_self_test", "offline_viewer_self_test", "combined_gui_self_test"):
        st = base[k]
        lines.append(
            f"- `{k}`: ok **{st['ok']}**, {st['n_checks']} checks, "
            f"{st['network_calls']} network calls, {st['js_errors']} JS errors")
    lines.extend([
        f"- external references across {len(base['artifacts'])} HTML artifacts: "
        f"**{base['external_refs_total']}**",
        f"- embedded ui_data contract: **{base['contract_version']}**",
        f"- tabs ({base['tab_count']}): " + ", ".join(base["tabs"]),
        "- artifacts: " + "; ".join(
            f"`{n}` {a['bytes']:,} bytes" for n, a in base["artifacts"].items()),
        f"- governance store: {base['governance_store']['change_records']} ChangeRecords, "
        f"{base['governance_store']['audit_entries']} audit entries, "
        f"{base['governance_store']['risk_register']} risk-register items",
        "",
        "## (b) Gap list vs the directive (priority order, ONE gap per cycle)",
        "",
    ])
    for g in note["gaps"]:
        lines.extend([
            f"### {g['gap_id']} (priority {g['priority']}) - {g['title']}",
            "",
            g["description"],
            "",
            f"- contract change: {g['contract_change']}",
            "",
            "**(c) Pre-registered acceptance criteria:**",
            "",
        ])
        lines.extend(f"- {c}" for c in g["acceptance_criteria"])
        lines.append("")
    ep = note["execution_plan"]
    lines.extend([
        "## Execution plan",
        "",
        f"- {ep['ordering']}",
        f"- completion: {ep['completion']}",
        f"- governance: {ep['governance']}",
        "",
        "## Task 1 gate",
        "",
        f"- ok: **{gate['ok']}** ({gate['n_checks']} checks)",
    ])
    lines.extend(f"- {k}: {v}" for k, v in gate["checks"].items())
    lines.extend(["", "*Generated by scripts/build_phase32_task1_design_note.py.*", ""])
    return "\n".join(lines)


def _card(note: dict, gate: dict) -> str:
    base = note["baseline_audit"]
    return "\n".join([
        "# UI Consolidation Design Card (Phase 32)",
        "",
        f"- Design note: `{DOC_ID}` v{DOC_VERSION} - gate "
        f"{'PASS' if gate['ok'] else 'FAIL'} ({gate['n_checks']} checks)",
        f"- Baseline: 3 offline self-tests green ({base['ui_app_self_test']['n_checks']}"
        f"/{base['offline_viewer_self_test']['n_checks']}"
        f"/{base['combined_gui_self_test']['n_checks']} checks), 0 network, 0 JS errors, "
        f"0 external refs, contract {base['contract_version']}, {base['tab_count']} tabs",
        "- Gaps (one per cycle): G1 owner-decision-pack surface (-> 1.14.0 additive); "
        "G2 user-input run-result surface; G3 governed read-out completeness sweep",
        "- Constraints: additive-only contract changes; zero-install preserved; "
        "display layer never recomputes; NO model parameter changes; "
        "Phase 30 binding stop-rule stands",
        "- Detail: `docs/validation/PHASE32_TASK1_DESIGN_NOTE.{json,md}`",
        "",
    ])


def apply_governance(store: GovernanceStore, note: dict, gate: dict) -> dict:
    actor = "Phase32Task1UIConsolidationDesign"
    phase = "Phase 32: Zero-Install Offline UI Consolidation"
    if any(r.title == CHANGE_TITLE for r in store.change_records):
        return {"added": False, "reason": "already applied (idempotent)"}
    base = note["baseline_audit"]
    rec = ChangeRecord.create(
        title=CHANGE_TITLE,
        description=(
            "Pre-registered the Phase 32 zero-install offline UI consolidation "
            "pass per the standing scheduled-task directive. (a) Baseline audit "
            "measured and frozen: ui_app (172 checks) / offline_viewer (11) / "
            "combined_gui (27) self-tests all ok:true with 0 network calls and "
            "0 JS errors; 0 external references across the three HTML "
            "artifacts; embedded contract 1.13.0; 13 tabs. (b) Three gaps "
            "pre-registered in priority order, one per cycle: G1 browsable "
            "owner-decision-pack surface (contract 1.13.0 -> 1.14.0 ADDITIVE, "
            "figures bit-for-bit from the assembled pack, neutrality and blank "
            "decision record preserved); G2 user-input run-result surface "
            "(Phase UIL outputs incl. currency/output_label provenance); G3 "
            "governed read-out completeness sweep. (c) Acceptance criteria "
            "pre-registered per gap + common criteria (self-tests green, "
            "additive-only, zero-install, no recomputation in display layer). "
            "Gate PASS with LIVE repo cross-checks. NO model parameter "
            "changes; binding stop-rule honoured."
        ),
        change_type="governance_change",
        affected_components=AFFECTED_COMPONENTS,
        standard_references=STANDARD_REFERENCES,
        before_snapshot={
            "design_note_exists": False,
            "ui_contract": base["contract_version"],
            "phase31": "COMPLETE (owner decision pending with model owner)",
        },
        after_snapshot={
            "design_note_exists": True,
            "doc_id": DOC_ID,
            "doc_version": DOC_VERSION,
            "gate_ok": gate["ok"],
            "gate_checks": gate["n_checks"],
            "gaps_preregistered": [g["gap_id"] for g in note["gaps"]],
            "ui_contract": base["contract_version"],
            "ui_contract_bump": False,
        },
        impact_assessment=(
            "Governance only. No artifact, contract, or model change this "
            "cycle; the note binds Tasks 2-4 to additive-only, zero-install, "
            "display-only changes with pre-registered acceptance criteria. "
            "The governed frozen-t headline is untouched."
        ),
        author=actor,
        phase=phase,
        quantitative_impact=(
            "None (design note). Baseline frozen: contract 1.13.0; 13 tabs; "
            "self-test checks 172/11/27; external refs 0. No governed capital "
            "figure changed."
        ),
    )
    rec.submit_for_peer_review(
        actor=actor,
        comments="Design note: gate PASS incl. live repo cross-checks; tests added.")
    rec.submit_to_owner(
        actor=actor,
        comments=(
            "Owner review: consolidation scope and gap priority (G1 owner pack "
            "surface first). No model or contract change until Task 2."
        ),
    )
    store.add_change_record(rec)
    store.audit_trail.append(AuditEntry.governance(
        actor=actor,
        phase=phase,
        event="ChangeRecord opened (OWNER_REVIEW) - Phase 32 Task 1 UI consolidation design note",
        details={"record_id": rec.record_id, "change_type": "governance_change",
                 "status": rec.status.value, "affected_components": AFFECTED_COMPONENTS},
    ))
    return {"added": True, "record_id": rec.record_id, "status": rec.status.value}


def main(use_governance: bool = False) -> dict:
    note = design_note()
    gate = validate_design_note(note, repo_root=".")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump({"design_note": note, "task1_gate": gate}, fh, indent=1, default=float)
    with open(MD_PATH, "w", encoding="utf-8") as fh:
        fh.write(_md(note, gate))
    with open(CARD_PATH, "w", encoding="utf-8") as fh:
        fh.write(_card(note, gate))
    out = {"verdict": "PASS" if gate["ok"] else "FAIL", "gate_ok": gate["ok"],
           "n_checks": gate["n_checks"],
           "failed": [k for k, v in gate["checks"].items() if not v],
           "json": JSON_PATH, "md": MD_PATH, "card": CARD_PATH}
    if use_governance and gate["ok"]:
        store = GovernanceStore.from_json(open(GOV_PATH).read())
        gov = apply_governance(store, note, gate)
        if gov.get("added"):
            with open(GOV_PATH, "w", encoding="utf-8") as fh:
                fh.write(store.to_json())
        gov["audit_entries"] = len(store.audit_trail.all())
        gov["audit_integrity_ok"] = store.audit_trail.verify_all()
        gov["change_records_total"] = len(store.change_records)
        out["governance"] = gov
    return out


if __name__ == "__main__":
    print(json.dumps(main(use_governance="--governance" in sys.argv), indent=1, default=str))
