"""Post-Phase-IGUI Task 3 - design-note builder (pre-registration only).

Pre-registers ONE stochastic-model improvement candidate - inner-path antithetic /
CRN variance reduction for the TVOG estimator (MR-VR-1) - with fixed acceptance
gates, Phase-30-stop-rule bound. Pure governance: NO model parameter change, NO new
copula-structure candidate, implementation DEFERRED to next cycle.

Outputs:
  docs/validation/POSTIGUI_TASK3_DESIGN_NOTE.{json,md}
  docs/POSTIGUI_VARIANCE_REDUCTION_DESIGN_CARD.md
  optional governance ChangeRecord (--governance), governance_change, OWNER_REVIEW.
"""

from __future__ import annotations

import json
import os
import sys

from par_model_v2.projection.variance_reduction_design import (
    CANDIDATE_ID,
    CANDIDATE_TITLE,
    COMPLETED_PRIOR_CANDIDATE_ID,
    FROZEN_T_COMPONENT_SCR_REFERENCE,
    NESTED_PATHWISE_SCR_REFERENCE,
    NEXT_CANDIDATE_ID,
    affected_components,
    design_note,
    standard_references,
    validate_design_note,
)
from par_model_v2.governance.audit_trail import AuditEntry, ChangeRecord, GovernanceStore

GOV_PATH = os.path.join(".claude-dev", "GOVERNANCE_STORE.json")
OUT_DIR = os.path.join("docs", "validation")
JSON_PATH = os.path.join(OUT_DIR, "POSTIGUI_TASK3_DESIGN_NOTE.json")
MD_PATH = os.path.join(OUT_DIR, "POSTIGUI_TASK3_DESIGN_NOTE.md")
CARD_PATH = os.path.join("docs", "POSTIGUI_VARIANCE_REDUCTION_DESIGN_CARD.md")

CHANGE_TITLE = (
    "Post-Phase-IGUI Task 3 - design note: pre-register ONE model-improvement "
    "candidate (MR-VR-1 inner-path antithetic/CRN variance reduction for the TVOG "
    "estimator, Phase 30 stop-rule bound)"
)


def _md(note: dict, gate: dict) -> str:
    lines = [
        f"# {note['title']}",
        "",
        f"**Verdict: {'PASS' if gate['ok'] else 'FAIL'}** - pure governance "
        f"({note['change_type']}); NO parameter change; implementation DEFERRED. "
        f"Classification: {note['classification']}.",
        "",
        "## 1. Candidate (pre-registered, exactly one)",
        "",
        f"- **{note['candidate_id']}** - {note['candidate_title']}",
        f"- Touches copula structure: **{note['touches_copula_structure']}** "
        f"(Phase 30 stop-rule compliant)",
        f"- No model parameter change: **{note['no_model_parameter_changes']}**; "
        f"implementation deferred: **{note['implementation_deferred']}**",
        f"- Techniques under study: {', '.join(note['vr_techniques'])}",
        "",
        "## 2. Context",
        "",
        note["context"],
        "",
        "Frozen cross-check references:",
        "",
        f"- Governed frozen-t component SCR: **{note['frozen_references']['frozen_t_component_scr']:,.6f}**",
        f"- Nested path-wise reference: {note['frozen_references']['nested_pathwise_scr']:,.1f}",
        "- Variance-reduction ratio precedents (outer basis, work-normalised):",
        "",
    ]
    for k, v in note["frozen_references"]["vr_ratio_precedents"].items():
        lines.append(f"  - {k}: {v:g}x")
    lines.extend([
        "",
        "## 3. Scope deferred to next cycle (implementation)",
        "",
    ])
    lines.extend(f"- {s}" for s in note["scope_deferred_next_cycle"])
    lines.extend(["", "## 4. Pre-registered acceptance gates (frozen now)", ""])
    for g in note["acceptance_gates"]:
        lines.append(f"- **{g['id']} {g['name']}** - {g['criterion']}")
    seq = note["candidate_sequencing"]
    lines.extend([
        "",
        "## 5. Candidate sequencing (pool of three)",
        "",
        f"- Completed prior: **{seq['completed_prior']}** (credentialled-data calibration diagnostics, done at Task 2)",
        f"- Selected NOW: **{seq['selected_now']}** (inner-path antithetic/CRN variance reduction for TVOG)",
        f"- Next candidate: **{seq['next_candidate']}** (mortality-trend / longevity 5th driver - parameter-adding, owner sign-off)",
        f"- Rationale: {seq['rationale']}",
        "",
        "## 6. Stop-rule compliance",
        "",
        note["stop_rule_compliance"],
        "",
        "## 7. Validation gate",
        "",
        f"- ok: **{gate['ok']}** ({gate['n_checks']} checks)",
    ])
    lines.extend(f"- {k}: {v}" for k, v in gate["checks"].items())
    lines.extend(["", "## 8. Standards", ""])
    lines.extend(f"- {s}" for s in note["standard_references"])
    lines.extend([
        "",
        "*Generated by scripts/build_postigui_task3_design_note.py.*",
        "",
    ])
    return "\n".join(lines)


def _card(note: dict) -> str:
    return "\n".join([
        "# Inner-Path Variance Reduction (TVOG) - Design Card "
        "(Post-Phase-IGUI Task 3)",
        "",
        f"**{note['candidate_id']} - {note['candidate_title']}.** Pure governance "
        f"pre-registration; NO parameter change; implementation DEFERRED. "
        f"{note['classification']} only.",
        "",
        "## What it would do (next cycle, gated)",
        "",
        "Run a DISCLOSED efficiency study on the inner-path / nested-stochastic TVOG "
        "estimator: compare crude i.i.d. Monte Carlo against antithetic pairing, "
        "common-random-numbers (CRN) across the guarantee on/off legs, and an optional "
        "Sobol-RQMC inner grid - all on the SAME governed outer states. Report "
        "unbiasedness (mean over >= 200 replicate seeds within 0.5% of crude), "
        "work-normalised variance-reduction ratios with CIs, and the inner-path count "
        "n* for a target SE. The governed production estimator and headline SCR "
        f"({FROZEN_T_COMPONENT_SCR_REFERENCE:,.1f}) stay BIT-IDENTICAL - this is "
        "measurement, not adoption.",
        "",
        "## Why now",
        "",
        "MR-CAL-1 calibration diagnostics completed at Task 2 (margin residual 8.15% of "
        "the nested gap; copula-FORM dominates). With model FORM frozen by the Phase 30 "
        "binding stop-rule, the next worthwhile gain is NUMERICAL: the inner-path TVOG "
        "estimator is the most compute-intensive part of a run and its variance sets the "
        "inner-path budget. Antithetic and CRN are standard, bias-free levers; the study "
        "must MEASURE inner-path efficacy (antithetic is expected-ineffective at 99.5%).",
        "",
        "## Sequencing",
        "",
        f"1. **{COMPLETED_PRIOR_CANDIDATE_ID}** credentialled-data calibration diagnostics (COMPLETE, Task 2).",
        f"2. **{CANDIDATE_ID}** inner-path antithetic/CRN variance reduction for TVOG (selected now).",
        f"3. **{NEXT_CANDIDATE_ID}** longevity 5th driver (deferred; needs owner sign-off).",
        "",
        "*Generated by scripts/build_postigui_task3_design_note.py.*",
        "",
    ])


def apply_governance(store: GovernanceStore, note: dict, gate: dict) -> dict:
    actor = "PostIGUITask3VarianceReductionDesignNote"
    phase = "Post-Phase-IGUI: Model-Improvement Candidate Pre-Registration"
    if any(r.title == CHANGE_TITLE for r in store.change_records):
        return {"added": False, "reason": "already applied (idempotent)"}
    rec = ChangeRecord.create(
        title=CHANGE_TITLE,
        description=(
            "Design note pre-registering exactly ONE stochastic-model improvement "
            "candidate (MR-VR-1: inner-path antithetic/CRN variance reduction for the "
            "TVOG estimator) with six fixed acceptance gates and a governed-headline "
            "invariance requirement. Efficiency study only, no estimator adoption; "
            "MR-CAL-1 is COMPLETE (Task 2) and MR-LONGEV-1 (longevity 5th driver) stays "
            "deferred. No capital output changed; no new copula-structure candidate "
            "(Phase 30 binding stop-rule); MR-016/MR-017 untouched."
        ),
        change_type="governance_change",
        affected_components=affected_components(),
        standard_references=standard_references(),
        before_snapshot={
            "frontier": "Post-Phase-IGUI Task 2 COMPLETE (MR-CAL-1 implemented)",
            "mr016": "OPEN (stop-rule applied; dependence-FORM escalation ended)",
            "mr017": "OPEN (vine-form limitations)",
            "next_task": "Post-Phase-IGUI Task 3 model-improvement candidate design note",
        },
        after_snapshot={
            "candidate_id": CANDIDATE_ID,
            "completed_prior": COMPLETED_PRIOR_CANDIDATE_ID,
            "next_candidate": NEXT_CANDIDATE_ID,
            "acceptance_gates": [g["id"] for g in note["acceptance_gates"]],
            "validation_gate_ok": gate["ok"],
            "implementation": "DEFERRED to next cycle (gated)",
        },
        impact_assessment=(
            "Governance only. Freezes the candidate identity, scope and acceptance "
            "gates before any implementation; the governed frozen-t headline is "
            "unchanged and no model parameter moves. Only the Monte Carlo sampling "
            "scheme of an existing estimator would change. Stop-rule honoured (no "
            "copula structure touched)."
        ),
        author=actor,
        phase=phase,
        quantitative_impact=(
            f"Registered references only: governed headline "
            f"{FROZEN_T_COMPONENT_SCR_REFERENCE:,.6f}; nested "
            f"{NESTED_PATHWISE_SCR_REFERENCE:,.1f}; VR ratio precedents (outer basis) "
            "{sobol 2.76x-7.1x helpful / antithetic 0.72x-0.78x expected-ineffective at "
            "99.5%}. No governed capital figures changed."
        ),
    )
    rec.submit_for_peer_review(
        actor=actor,
        comments="Candidate pre-registration + six fixed gates + sequencing; scaffold tests added.",
    )
    rec.submit_to_owner(
        actor=actor,
        comments="Owner review: pure governance pre-registration; implementation deferred to next cycle.",
    )
    store.add_change_record(rec)
    store.audit_trail.append(AuditEntry.governance(
        actor=actor,
        phase=phase,
        event="ChangeRecord opened (OWNER_REVIEW) - Post-Phase-IGUI Task 3 candidate design note",
        details={"record_id": rec.record_id, "change_type": "governance_change",
                 "status": rec.status.value, "candidate_id": CANDIDATE_ID},
    ))
    return {"added": True, "record_id": rec.record_id, "status": rec.status.value}


def main(use_governance: bool = False) -> dict:
    note = design_note()
    gate = validate_design_note(note)
    note["validation_gate"] = gate
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(note, fh, indent=1, default=float)
    with open(MD_PATH, "w", encoding="utf-8") as fh:
        fh.write(_md(note, gate))
    with open(CARD_PATH, "w", encoding="utf-8") as fh:
        fh.write(_card(note))
    out = {"verdict": "PASS" if gate["ok"] else "FAIL", "gate_ok": gate["ok"],
           "n_checks": gate["n_checks"], "candidate_id": CANDIDATE_ID,
           "json": JSON_PATH, "md": MD_PATH, "card": CARD_PATH}
    if use_governance:
        store = GovernanceStore.from_json(open(GOV_PATH).read())
        gov = apply_governance(store, note, gate)
        if gov.get("added"):
            with open(GOV_PATH, "w", encoding="utf-8") as fh:
                fh.write(store.to_json())
        gov["audit_entries"] = len(store.audit_trail.all())
        gov["audit_integrity_ok"] = store.audit_trail.verify_all()
        gov["change_records_total"] = len(store.change_records)
        out["governance"] = gov
    return out


if __name__ == "__main__":
    res = main(use_governance="--governance" in sys.argv)
    print(json.dumps(res, indent=1, default=str))
